import { calculateGroupBalances, calculateSettlementAwareBalances, suggestSettlements } from './group-balances';

const members=[{id:'a',name:'A',email:'a@example.test'},{id:'b',name:'B',email:'b@example.test'},{id:'c',name:'C',email:'c@example.test'}];
describe('calculateGroupBalances',()=>{
  it('is deterministic for unequal shares and a single payer covering everyone',()=>{expect(calculateGroupBalances(members,[{paidByUserId:'a',shares:[{userId:'a',amountMinor:100},{userId:'b',amountMinor:200},{userId:'c',amountMinor:700}]}])).toEqual([{userId:'a',name:'A',email:'a@example.test',paidMinor:1000,owedMinor:100,netMinor:900},{userId:'b',name:'B',email:'b@example.test',paidMinor:0,owedMinor:200,netMinor:-200},{userId:'c',name:'C',email:'c@example.test',paidMinor:0,owedMinor:700,netMinor:-700}]);});
  it('aggregates multiple expenses and members using integer minor units',()=>{const balances=calculateGroupBalances(members,[{paidByUserId:'a',shares:[{userId:'a',amountMinor:500},{userId:'b',amountMinor:500}]},{paidByUserId:'b',shares:[{userId:'a',amountMinor:300},{userId:'b',amountMinor:300},{userId:'c',amountMinor:400}]}]);expect(balances.map(({userId,paidMinor,owedMinor,netMinor})=>({userId,paidMinor,owedMinor,netMinor}))).toEqual([{userId:'a',paidMinor:1000,owedMinor:800,netMinor:200},{userId:'b',paidMinor:1000,owedMinor:800,netMinor:200},{userId:'c',paidMinor:0,owedMinor:400,netMinor:-400}]);});
  it('applies partial, full, and multiple settlements to final balances',()=>{const expenses=[{paidByUserId:'a',shares:[{userId:'a',amountMinor:200},{userId:'b',amountMinor:800}]}];const partial=calculateSettlementAwareBalances(members,expenses,[{fromUserId:'b',toUserId:'a',amountMinor:300}]);expect(partial.find(x=>x.userId==='b')).toMatchObject({settledOutgoingMinor:300,netMinor:-500});expect(partial.find(x=>x.userId==='a')).toMatchObject({settledIncomingMinor:300,netMinor:500});const full=calculateSettlementAwareBalances(members,expenses,[{fromUserId:'b',toUserId:'a',amountMinor:800}]);expect(full.map(x=>x.netMinor)).toEqual([0,0,0]);const multiple=calculateSettlementAwareBalances(members,expenses,[{fromUserId:'b',toUserId:'a',amountMinor:200},{fromUserId:'b',toUserId:'a',amountMinor:100}]);expect(multiple.find(x=>x.userId==='b')?.settledOutgoingMinor).toBe(300);});
  it('suggests deterministic transfers with no zero-balance members',()=>{const balances=calculateSettlementAwareBalances(members,[{paidByUserId:'a',shares:[{userId:'a',amountMinor:100},{userId:'b',amountMinor:300},{userId:'c',amountMinor:600}]}],[]);expect(suggestSettlements(balances)).toEqual([{fromUserId:'b',toUserId:'a',amountMinor:300},{fromUserId:'c',toUserId:'a',amountMinor:600}]);});
});
