import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { GroupRole, Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { calculateSettlementAwareBalances, suggestSettlements } from './group-balances';
import { CreateSettlementDto } from './dto/create-settlement.dto';
const safeUser={id:true,name:true,email:true} as const;
@Injectable()
export class GroupSettlementsService {
 constructor(private readonly prisma:PrismaService) {}
 async create(actorId:string,groupId:string,dto:CreateSettlementDto){try{return await this.prisma.$transaction(async tx=>{const balances=await this.loadBalances(tx,actorId,groupId);if(dto.toUserId===actorId)throw new BadRequestException('A settlement recipient must be another group member.');const payer=balances.find(item=>item.userId===actorId),recipient=balances.find(item=>item.userId===dto.toUserId);if(!recipient)throw new BadRequestException('Settlement recipient must be a group member.');if(!payer||payer.netMinor>=0)throw new BadRequestException('Only a member with an outstanding debt can pay a settlement.');if(recipient.netMinor<=0)throw new BadRequestException('Settlement recipient must have an outstanding credit.');if(dto.amountMinor>-payer.netMinor)throw new BadRequestException('Settlement exceeds the payer’s outstanding debt.');if(dto.amountMinor>recipient.netMinor)throw new BadRequestException('Settlement exceeds the recipient’s outstanding credit.');return tx.settlement.create({data:{groupId,fromUserId:actorId,toUserId:dto.toUserId,amountMinor:dto.amountMinor,settledAt:new Date()},include:{fromUser:{select:safeUser},toUser:{select:safeUser}}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}catch(error:unknown){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2034')throw new ConflictException('Settlement conflicted with another update. Please retry.');throw error;}}
 async findAll(actorId:string,groupId:string){await this.member(actorId,groupId);return this.prisma.settlement.findMany({where:{groupId},orderBy:[{settledAt:'desc'},{createdAt:'desc'}],include:{fromUser:{select:safeUser},toUser:{select:safeUser}}});}
 async remove(actorId:string,groupId:string,settlementId:string){return this.prisma.$transaction(async tx=>{const membership=await this.member(actorId,groupId,tx);const settlement=await tx.settlement.findFirst({where:{id:settlementId,groupId}});if(!settlement)throw new NotFoundException('Settlement not found.');if(settlement.fromUserId!==actorId&&membership.role!==GroupRole.OWNER)throw new ForbiddenException('Only the settlement payer or group owner can delete it.');await tx.settlement.delete({where:{id:settlementId}});return {deleted:true};});}
 async balances(actorId:string,groupId:string){return this.loadBalances(this.prisma,actorId,groupId);}
 async suggestions(actorId:string,groupId:string){return suggestSettlements(await this.balances(actorId,groupId));}
 private async loadBalances(db:Prisma.TransactionClient|PrismaService,actorId:string,groupId:string){await this.member(actorId,groupId,db);const [members,expenses,settlements]=await Promise.all([db.groupMember.findMany({where:{groupId},include:{user:{select:safeUser}},orderBy:{joinedAt:'asc'}}),db.expense.findMany({where:{groupId,deletedAt:null},select:{paidByUserId:true,shares:{select:{userId:true,amountMinor:true}}}}),db.settlement.findMany({where:{groupId},select:{fromUserId:true,toUserId:true,amountMinor:true}})]);return calculateSettlementAwareBalances(members.map(item=>item.user),expenses,settlements);}
 private async member(userId:string,groupId:string,db:Prisma.TransactionClient|PrismaService=this.prisma){const membership=await db.groupMember.findUnique({where:{groupId_userId:{groupId,userId}}});if(!membership)throw new NotFoundException('Group not found.');return membership;}
}
