import { BadRequestException, ForbiddenException, NotFoundException } from '@nestjs/common';
import { GroupRole } from '@prisma/client';
import { GroupSettlementsService } from './group-settlements.service';
const groupId='11111111-1111-4111-8111-111111111111'; const payer='22222222-2222-4222-8222-222222222222'; const creditor='33333333-3333-4333-8333-333333333333'; const owner='44444444-4444-4444-8444-444444444444'; const outsider='55555555-5555-4555-8555-555555555555'; const settlementId='66666666-6666-4666-8666-666666666666';
describe('GroupSettlementsService',()=>{
 let tx:any;let prisma:any;let service:GroupSettlementsService;
 beforeEach(()=>{tx={groupMember:{findUnique:jest.fn(async({where}:any)=>{const id=where.groupId_userId.userId;return where.groupId_userId.groupId===groupId&&[payer,creditor,owner].includes(id)?{userId:id,role:id===owner?GroupRole.OWNER:GroupRole.MEMBER}:null;}),findMany:jest.fn(async()=>[{user:{id:payer,name:'Payer',email:'payer@test'}},{user:{id:creditor,name:'Creditor',email:'creditor@test'}},{user:{id:owner,name:'Owner',email:'owner@test'}}])},expense:{findMany:jest.fn(async()=>[{paidByUserId:creditor,shares:[{userId:payer,amountMinor:700},{userId:creditor,amountMinor:300}]}])},settlement:{findMany:jest.fn(async()=>[]),create:jest.fn(async({data}:any)=>data),findFirst:jest.fn(async({where}:any)=>where.groupId===groupId?{id:settlementId,groupId,fromUserId:payer,toUserId:creditor}:null),delete:jest.fn(async()=>({}))}};prisma={$transaction:jest.fn(async(work:any)=>work(tx)),...tx};service=new GroupSettlementsService(prisma);});
 it('creates settlements only from debtors to creditors and rechecks balances in a transaction',async()=>{const result:any=await service.create(payer,groupId,{toUserId:creditor,amountMinor:500});expect(prisma.$transaction).toHaveBeenCalled();expect(result).toMatchObject({groupId,fromUserId:payer,toUserId:creditor,amountMinor:500});await expect(service.create(payer,groupId,{toUserId:creditor,amountMinor:701})).rejects.toBeInstanceOf(BadRequestException);await expect(service.create(creditor,groupId,{toUserId:payer,amountMinor:1})).rejects.toBeInstanceOf(BadRequestException);});
 it('rejects cross-group recipients and actors',async()=>{await expect(service.create(payer,groupId,{toUserId:outsider,amountMinor:1})).rejects.toBeInstanceOf(BadRequestException);await expect(service.create(outsider,groupId,{toUserId:creditor,amountMinor:1})).rejects.toBeInstanceOf(NotFoundException);});
 it('allows the payer or group owner to delete but not unrelated members',async()=>{await service.remove(payer,groupId,settlementId);await service.remove(owner,groupId,settlementId);tx.groupMember.findUnique.mockResolvedValueOnce({userId:creditor,role:GroupRole.MEMBER});await expect(service.remove(creditor,groupId,settlementId)).rejects.toBeInstanceOf(ForbiddenException);await expect(service.remove(payer,'77777777-7777-4777-8777-777777777777',settlementId)).rejects.toBeInstanceOf(NotFoundException);});
});
