import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { calculateGroupBalances } from './group-balances';
import { CreateGroupExpenseDto, type ExpenseShareDto, UpdateGroupExpenseDto } from './dto/group-expense.dto';

const safeUser={id:true,name:true,email:true} as const;
const expenseInclude={category:{select:{id:true,name:true}},user:{select:safeUser},paidByUser:{select:safeUser},shares:{include:{user:{select:safeUser}}}} as const;
@Injectable()
export class GroupExpensesService {
  constructor(private readonly prisma:PrismaService) {}
  async create(actorId:string,groupId:string,dto:CreateGroupExpenseDto){return this.prisma.$transaction(async tx=>{await this.validate(tx,actorId,groupId,dto.paidByUserId,dto.categoryId,dto.amountMinor,dto.shares);return tx.expense.create({data:{userId:actorId,groupId,paidByUserId:dto.paidByUserId,categoryId:dto.categoryId,amountMinor:dto.amountMinor,currency:dto.currency,description:dto.description.trim(),expenseDate:this.date(dto.expenseDate),shares:{create:dto.shares}},include:expenseInclude});});}
  async findAll(actorId:string,groupId:string){await this.member(actorId,groupId);return this.prisma.expense.findMany({where:{groupId,deletedAt:null},orderBy:[{expenseDate:'desc'},{createdAt:'desc'}],include:expenseInclude});}
  async findOne(actorId:string,groupId:string,expenseId:string){await this.member(actorId,groupId);const expense=await this.prisma.expense.findFirst({where:{id:expenseId,groupId,deletedAt:null},include:expenseInclude});if(!expense)throw new NotFoundException('Group expense not found.');return expense;}
  async update(actorId:string,groupId:string,expenseId:string,dto:UpdateGroupExpenseDto){return this.prisma.$transaction(async tx=>{await this.member(actorId,groupId,tx);const existing=await tx.expense.findFirst({where:{id:expenseId,groupId,deletedAt:null}});if(!existing)throw new NotFoundException('Group expense not found.');if(existing.userId!==actorId)throw new ForbiddenException('Only the expense creator can update it.');const amount=dto.amountMinor??existing.amountMinor,payer=dto.paidByUserId??existing.paidByUserId,category=dto.categoryId??existing.categoryId;await this.validate(tx,actorId,groupId,payer,category,amount,dto.shares);await tx.expenseShare.deleteMany({where:{expenseId}});return tx.expense.update({where:{id:expenseId},data:{amountMinor:amount,paidByUserId:payer,categoryId:category,...(dto.currency!==undefined&&{currency:dto.currency}),...(dto.description!==undefined&&{description:dto.description.trim()}),...(dto.expenseDate!==undefined&&{expenseDate:this.date(dto.expenseDate)}),version:{increment:1},shares:{create:dto.shares}},include:expenseInclude});});}
  async remove(actorId:string,groupId:string,expenseId:string){return this.prisma.$transaction(async tx=>{await this.member(actorId,groupId,tx);const expense=await tx.expense.findFirst({where:{id:expenseId,groupId,deletedAt:null}});if(!expense)throw new NotFoundException('Group expense not found.');if(expense.userId!==actorId)throw new ForbiddenException('Only the expense creator can delete it.');await tx.expenseShare.deleteMany({where:{expenseId}});return tx.expense.update({where:{id:expenseId},data:{deletedAt:new Date(),version:{increment:1}}});});}
  async balances(actorId:string,groupId:string){await this.member(actorId,groupId);const [members,expenses]=await Promise.all([this.prisma.groupMember.findMany({where:{groupId},include:{user:{select:safeUser}},orderBy:{joinedAt:'asc'}}),this.prisma.expense.findMany({where:{groupId,deletedAt:null},select:{paidByUserId:true,shares:{select:{userId:true,amountMinor:true}}}})]);return calculateGroupBalances(members.map(item=>item.user),expenses);}
  private async validate(tx:Prisma.TransactionClient,actorId:string,groupId:string,payerId:string,categoryId:string,amount:number,shares:readonly ExpenseShareDto[]){const members=await tx.groupMember.findMany({where:{groupId},select:{userId:true}});const ids=new Set(members.map(member=>member.userId));if(!ids.has(actorId))throw new NotFoundException('Group not found.');if(!ids.has(payerId))throw new BadRequestException('Payer must be a group member.');const seen=new Set<string>();let total=0;for(const share of shares){if(seen.has(share.userId))throw new BadRequestException('A member can only have one share.');seen.add(share.userId);if(!ids.has(share.userId))throw new BadRequestException('Every share user must be a group member.');if(!Number.isInteger(share.amountMinor)||share.amountMinor<1)throw new BadRequestException('Share amounts must be positive integers.');total+=share.amountMinor;}if(total!==amount)throw new BadRequestException('Share amounts must equal the expense amount.');const category=await tx.category.findFirst({where:{id:categoryId,userId:actorId}});if(!category)throw new NotFoundException('Category not found.');}
  private async member(userId:string,groupId:string,tx:Prisma.TransactionClient|PrismaService=this.prisma){const membership=await tx.groupMember.findUnique({where:{groupId_userId:{groupId,userId}}});if(!membership)throw new NotFoundException('Group not found.');return membership;}
  private date(value:string){return new Date(`${value}T00:00:00.000Z`);}
}
