import assert from 'node:assert/strict';
import test from 'node:test';
import { createCategoryCache } from './category-cache-core';
import type { ConnectivityState } from './sync-connectivity-core';
const online:ConnectivityState={isConnected:true,isInternetReachable:true};const offline:ConnectivityState={isConnected:false,isInternetReachable:false};
function setup(initial:ConnectivityState=offline){let listener:((state:ConnectivityState)=>void)|undefined;let subscriptions=0;let refreshes=0;let reject=false;const cache=createCategoryCache({addEventListener:next=>{subscriptions++;listener=next;return ()=>{listener=undefined;};},fetch:async()=>initial,refresh:async()=>{refreshes++;if(reject)throw new Error('API unavailable');}});return {cache,emit:(state:ConnectivityState)=>listener?.(state),reject:()=>{reject=true;},counts:()=>({subscriptions,refreshes})};}
test('prevents refresh before authenticated restoration and while logged out',async()=>{const test=setup(online);test.cache.updateAuth({isLoading:true,isAuthenticated:true});test.cache.updateAuth({isLoading:false,isAuthenticated:false});await Promise.resolve();assert.deepEqual(test.counts(),{subscriptions:0,refreshes:0});});
test('refreshes an online authenticated cache once',async()=>{const test=setup(online);test.cache.updateAuth({isLoading:false,isAuthenticated:true});await Promise.resolve();assert.deepEqual(test.counts(),{subscriptions:1,refreshes:1});});
test('preserves offline cached data by not refreshing while offline',async()=>{const test=setup(offline);test.cache.updateAuth({isLoading:false,isAuthenticated:true});await Promise.resolve();assert.equal(test.counts().refreshes,0);});
test('refreshes when transitioning from offline to online without duplicate requests',async()=>{const test=setup();test.cache.updateAuth({isLoading:false,isAuthenticated:true});await Promise.resolve();test.emit(offline);test.emit(online);test.emit(online);assert.equal(test.counts().refreshes,1);});
test('prevents a second refresh while the first request is active',async()=>{let listener:((state:ConnectivityState)=>void)|undefined;let resolveRefresh:()=>void=()=>{};let calls=0;const cache=createCategoryCache({addEventListener:next=>{listener=next;return ()=>{listener=undefined;};},fetch:async()=>online,refresh:async()=>{calls++;await new Promise<void>(resolve=>{resolveRefresh=resolve;});}});cache.updateAuth({isLoading:false,isAuthenticated:true});await Promise.resolve();listener?.(offline);listener?.(online);assert.equal(calls,1);resolveRefresh();});
test('contains API errors and allows a later refresh',async()=>{const test=setup(online);test.reject();test.cache.updateAuth({isLoading:false,isAuthenticated:true});await new Promise(resolve=>setTimeout(resolve,0));test.emit(offline);test.emit(online);await Promise.resolve();assert.equal(test.counts().refreshes,2);});
