import { toApiError } from '../api/client';
import { uploadReceipt,type ReceiptUploadFile } from '../api/receipt-service';
import { getDatabase } from '../db/database';
import { claimReceiptUpload,listPendingReceiptUploads,markReceiptUploadFailure,markReceiptUploadSuccess,recoverStaleReceiptUploads } from '../db/receipt-repository';
import type { LocalExpenseReceiptRecord } from '../db/types';
import { isRetryableReceiptFailure } from './receipt-sync-logic';
const staleMs=5*60_000;
const mimeFor=(uri:string):ReceiptUploadFile['type']=>uri.toLowerCase().endsWith('.png')?'image/png':uri.toLowerCase().endsWith('.webp')?'image/webp':'image/jpeg';
export interface ReceiptSyncDependencies {getDatabase:typeof getDatabase;list:(db:Awaited<ReturnType<typeof getDatabase>>,userId:string,limit?:number)=>Promise<LocalExpenseReceiptRecord[]>;recover:(db:Awaited<ReturnType<typeof getDatabase>>,userId:string,staleBefore:string,now:string)=>Promise<number>;claim:(db:Awaited<ReturnType<typeof getDatabase>>,userId:string,id:string,now:string)=>Promise<boolean>;success:(db:Awaited<ReturnType<typeof getDatabase>>,userId:string,id:string,remoteId:string,now:string)=>Promise<boolean>;failure:(db:Awaited<ReturnType<typeof getDatabase>>,userId:string,id:string,message:string,retryable:boolean,now:string)=>Promise<boolean>;upload:(expenseId:string,file:ReceiptUploadFile)=>Promise<{id:string}>;now:()=>Date;}
const production:ReceiptSyncDependencies={getDatabase,list:listPendingReceiptUploads,recover:recoverStaleReceiptUploads,claim:claimReceiptUpload,success:markReceiptUploadSuccess,failure:markReceiptUploadFailure,upload:uploadReceipt,now:()=>new Date()};
export function createReceiptSyncWorker(d:ReceiptSyncDependencies=production){let active=false;return {isActive:()=>active,async sync(userId:string){if(active)return;active=true;try{const db=await d.getDatabase(),time=d.now();await d.recover(db,userId,new Date(time.getTime()-staleMs).toISOString(),time.toISOString());while(true){const [receipt]=await d.list(db,userId,1);if(!receipt)return;if(!await d.claim(db,userId,receipt.id,d.now().toISOString()))continue;try{const remote=await d.upload(receipt.expenseId,{uri:receipt.localUri,name:`receipt-${receipt.id}.${mimeFor(receipt.localUri).split('/')[1]}`,type:mimeFor(receipt.localUri)});await d.success(db,userId,receipt.id,remote.id,d.now().toISOString());}catch(error){const apiError=toApiError(error),retryable=isRetryableReceiptFailure(apiError.status);await d.failure(db,userId,receipt.id,(apiError.message||'Receipt upload failed.').slice(0,500),retryable,d.now().toISOString());if(retryable)return;}}}finally{active=false;}}};}
const worker=createReceiptSyncWorker(); export const syncPendingReceipts=(userId:string)=>worker.sync(userId);
