import assert from 'node:assert/strict';
import test from 'node:test';
import { createSyncConnectivity, type ConnectivityState } from './sync-connectivity-core';

const online:ConnectivityState={isConnected:true,isInternetReachable:true};const offline:ConnectivityState={isConnected:false,isInternetReachable:false};
function setup(initial:ConnectivityState=offline){let listener:((state:ConnectivityState)=>void)|undefined;let subscriptions=0;let cleanups=0;let syncs=0;let reject=false;const controller=createSyncConnectivity({addEventListener:next=>{subscriptions++;listener=next;return ()=>{cleanups++;listener=undefined;};},fetch:async()=>initial,sync:async()=>{syncs++;if(reject)throw new Error('sync failed');}});return {controller,emit:(state:ConnectivityState)=>listener?.(state),setReject:(value:boolean)=>{reject=value;},counts:()=>({subscriptions,cleanups,syncs})};}
test('starts its listener only after authenticated restoration',async()=>{const test=setup();test.controller.updateAuth({isLoading:true,isAuthenticated:true});assert.equal(test.counts().subscriptions,0);test.controller.updateAuth({isLoading:false,isAuthenticated:true});await Promise.resolve();assert.equal(test.counts().subscriptions,1);});
test('does not listen while logged out',()=>{const test=setup();test.controller.updateAuth({isLoading:false,isAuthenticated:false});assert.deepEqual(test.counts(),{subscriptions:0,cleanups:0,syncs:0});});
test('performs an initial sync for an online authenticated session',async()=>{const test=setup(online);test.controller.updateAuth({isLoading:false,isAuthenticated:true});await Promise.resolve();assert.equal(test.counts().syncs,1);});
test('syncs only when connectivity transitions from offline to online',async()=>{const test=setup();test.controller.updateAuth({isLoading:false,isAuthenticated:true});await Promise.resolve();test.emit(offline);test.emit(online);test.emit(online);assert.equal(test.counts().syncs,1);});
test('does not sync for an offline initial state',async()=>{const test=setup(offline);test.controller.updateAuth({isLoading:false,isAuthenticated:true});await Promise.resolve();assert.equal(test.counts().syncs,0);});
test('cleans up on logout and disposal',async()=>{const test=setup();test.controller.updateAuth({isLoading:false,isAuthenticated:true});await Promise.resolve();test.controller.updateAuth({isLoading:false,isAuthenticated:false});assert.equal(test.counts().cleanups,1);test.controller.dispose();assert.equal(test.counts().cleanups,1);});
test('does not register duplicate listeners',async()=>{const test=setup();test.controller.updateAuth({isLoading:false,isAuthenticated:true});test.controller.updateAuth({isLoading:false,isAuthenticated:true});await Promise.resolve();assert.equal(test.counts().subscriptions,1);});
test('swallows asynchronous sync errors',async()=>{const test=setup();test.setReject(true);test.controller.updateAuth({isLoading:false,isAuthenticated:true});await Promise.resolve();test.emit(offline);test.emit(online);await Promise.resolve();assert.equal(test.counts().syncs,1);});
