import assert from 'node:assert/strict';
import test from 'node:test';
import { createSyncWorker, type SyncWorkerDependencies } from './sync-worker-core';
import type { LocalExpenseRecord, SyncQueueRecord } from '../db/types';

const stamp='2026-08-29T00:00:00.000Z';
const local:LocalExpenseRecord={id:'expense',userId:'user',categoryId:'category',amountMinor:100,currency:'USD',description:'local',expenseDate:'2026-08-29',createdAt:stamp,updatedAt:stamp,version:2,deletedAt:null,syncStatus:'PENDING'};
const server={...local,description:'server',version:3,updatedAt:'2026-08-29T01:00:00.000Z'};
const operation=(type:SyncQueueRecord['operationType']='CREATE',overrides:Partial<SyncQueueRecord>={}):SyncQueueRecord=>({operationId:`op-${type}`,entityType:'expense',entityId:'expense',operationType:type,payloadJson:JSON.stringify(type==='CREATE'?{amountMinor:100}:{description:'changed',baseVersion:1}),attempts:0,status:'PENDING',lastError:null,nextAttemptAt:null,createdAt:stamp,updatedAt:stamp,...overrides});

function setup(operations:SyncQueueRecord[],post:SyncWorkerDependencies['api']['post']){const events:string[]=[];const database={};const deps:SyncWorkerDependencies={getDatabase:async()=>database as never,getAuthState:()=>({isAuthenticated:true,user:{id:'user'}}),getToken:async()=>'token',api:{post},listDue:async()=>operations.length?[operations[0] as SyncQueueRecord]:[],recoverStale:async()=>0,claim:async(_db,record)=>{if(record.status!=='PENDING')return false;record.status='PROCESSING';events.push(`claim:${record.operationId}`);return true;},releaseClaim:async()=>{operations.shift();events.push('release');return true;},getExpense:async()=>local,complete:async(_db,record,expense)=>{events.push(`complete:${record.operationId}:${expense.version}:${expense.deletedAt??'active'}`);operations.shift();return true;},fail:async(_db,record,failure,retryable)=>{events.push(`fail:${record.operationId}:${retryable}:${failure.statusCode??'network'}`);operations.shift();return true;},conflict:async(_db,record,localExpense,serverExpense)=>{events.push(`conflict:${record.operationId}:${localExpense?.syncStatus}:${(serverExpense as {version:number}).version}`);operations.shift();return true;},now:()=>new Date(stamp),createId:()=> 'conflict-id'};return {worker:createSyncWorker(deps),events};}

test('synchronizes a create and preserves the server id and version',async()=>{const sent:unknown[]=[];const {worker,events}=setup([operation('CREATE')],async(_url,data)=>{sent.push(data);return {data:{status:'APPLIED',expense:{...server,id:'expense',version:1}}};});await worker.syncPendingOperations();assert.deepEqual(sent,[{operationId:'op-CREATE',operationType:'CREATE',entityId:'expense',payload:{amountMinor:100}}]);assert.deepEqual(events,['claim:op-CREATE','complete:op-CREATE:1:active']);});
test('synchronizes an update with its base version',async()=>{const sent:unknown[]=[];const {worker,events}=setup([operation('UPDATE')],async(_url,data)=>{sent.push(data);return {data:{status:'APPLIED',expense:server}};});await worker.syncPendingOperations();assert.deepEqual(sent,[{operationId:'op-UPDATE',operationType:'UPDATE',entityId:'expense',payload:{description:'changed'},baseVersion:1}]);assert.match(events[1]??'',/complete:op-UPDATE:3/);});
test('synchronizes a delete and preserves the server tombstone',async()=>{const deleted='2026-08-29T01:00:00.000Z';const {worker,events}=setup([operation('DELETE')],async()=>({data:{status:'APPLIED',expense:{...server,deletedAt:deleted,version:3}}}));await worker.syncPendingOperations();assert.deepEqual(events,['claim:op-DELETE',`complete:op-DELETE:3:${deleted}`]);});
test('processes due operations in creation order',async()=>{const first=operation('CREATE',{operationId:'first',createdAt:'2026-08-28T00:00:00.000Z'});const second=operation('UPDATE',{operationId:'second',createdAt:'2026-08-29T00:00:00.000Z'});const {worker,events}=setup([first,second],async()=>({data:{status:'APPLIED',expense:server}}));await worker.syncPendingOperations();assert.deepEqual(events.filter(event=>event.startsWith('claim:')),['claim:first','claim:second']);});
test('prevents duplicate worker runs',async()=>{let resolveRequest:()=>void=()=>{};const wait=new Promise<void>(resolve=>{resolveRequest=resolve;});let calls=0;const {worker}=setup([operation()],async()=>{calls++;await wait;return {data:{status:'APPLIED',expense:server}};});const first=worker.syncPendingOperations();while(calls===0)await new Promise(resolve=>setTimeout(resolve,0));await worker.syncPendingOperations();assert.equal(calls,1);resolveRequest();await first;assert.equal(worker.isActive(),false);});
test('records a retryable network failure',async()=>{const {worker,events}=setup([operation()],async()=>{throw {status:null,message:'Network unavailable'};});await worker.syncPendingOperations();assert.deepEqual(events,['claim:op-CREATE','fail:op-CREATE:true:network']);});
test('records a permanent 4xx failure',async()=>{const {worker,events}=setup([operation()],async()=>{throw {status:422,message:'Invalid expense'};});await worker.syncPendingOperations();assert.deepEqual(events,['claim:op-CREATE','fail:op-CREATE:false:422']);});
test('passes a maximum-attempt failure to the queue state machine',async()=>{const {worker,events}=setup([operation('CREATE',{attempts:2})],async()=>{throw {status:503,message:'Server error'};});await worker.syncPendingOperations();assert.deepEqual(events,['claim:op-CREATE','fail:op-CREATE:true:503']);});
test('stops immediately after a 401 and releases its claim',async()=>{const first=operation('CREATE',{operationId:'first'});const second=operation('CREATE',{operationId:'second'});const {worker,events}=setup([first,second],async()=>{throw {status:401,message:'Unauthorized'};});await worker.syncPendingOperations();assert.deepEqual(events,['claim:first','release']);});
test('stores a conflict without overwriting the local pending expense',async()=>{const {worker,events}=setup([operation('UPDATE')],async()=>({data:{status:'CONFLICT',expense:server}}));await worker.syncPendingOperations();assert.deepEqual(events,['claim:op-UPDATE','conflict:op-UPDATE:PENDING:3']);});
test('treats an idempotency replayed APPLIED response as success',async()=>{const {worker,events}=setup([operation('CREATE')],async()=>({data:{status:'APPLIED',expense:{...server,version:1}}}));await worker.syncPendingOperations();assert.deepEqual(events,['claim:op-CREATE','complete:op-CREATE:1:active']);});
