import type { SQLiteDatabase } from 'expo-sqlite';
import { isRetryableSyncError, type SyncFailure } from '../db/sync-queue-state';
import type { LocalExpenseRecord, SyncOperationType, SyncQueueRecord } from '../db/types';
const STALE_PROCESSING_MS=5*60_000;
type ServerExpense={id:string;userId?:string;categoryId:string|null;amountMinor:number;currency:string;description:string;expenseDate:string;createdAt:string;updatedAt:string;version:number;deletedAt:string|null;};type SyncResponse={status:'APPLIED'|'CONFLICT';expense:ServerExpense;};type AuthSnapshot={isAuthenticated:boolean;user:{id:string}|null};type ApiClient={post(url:string,data:unknown):Promise<{data:SyncResponse}>};
export interface SyncWorkerDependencies { getDatabase:()=>Promise<SQLiteDatabase>; getAuthState:()=>AuthSnapshot; getToken:()=>Promise<string|null>; api:ApiClient; listDue:(db:SQLiteDatabase,now:string,limit:number)=>Promise<SyncQueueRecord[]>; recoverStale:(db:SQLiteDatabase,staleBefore:string,now:string)=>Promise<number>; claim:(db:SQLiteDatabase,record:SyncQueueRecord,now:Date)=>Promise<boolean>; releaseClaim:(db:SQLiteDatabase,record:SyncQueueRecord,now:string)=>Promise<boolean>; getExpense:(db:SQLiteDatabase,id:string)=>Promise<LocalExpenseRecord|null>; complete:(db:SQLiteDatabase,record:SyncQueueRecord,expense:LocalExpenseRecord)=>Promise<boolean>; fail:(db:SQLiteDatabase,record:SyncQueueRecord,error:SyncFailure,retryable:boolean,now:Date)=>Promise<boolean>; conflict:(db:SQLiteDatabase,record:SyncQueueRecord,local:LocalExpenseRecord|null,server:unknown,id:string,now:string)=>Promise<boolean>; now:()=>Date; createId:()=>string; }
export function createSyncWorker(d:SyncWorkerDependencies){let active=false;return {isActive:()=>active,async syncPendingOperations():Promise<void>{if(active)return;active=true;try{const auth=d.getAuthState();if(!auth.isAuthenticated||!auth.user||!await d.getToken())return;const db=await d.getDatabase();const now=d.now();await d.recoverStale(db,new Date(now.getTime()-STALE_PROCESSING_MS).toISOString(),now.toISOString());while(true){const [op]=await d.listDue(db,d.now().toISOString(),1);if(!op)return;if(!await d.claim(db,op,d.now()))continue;if(await process(d,db,op)==='UNAUTHORIZED')return;}}finally{active=false;}}};}
async function process(d:SyncWorkerDependencies,db:SQLiteDatabase,op:SyncQueueRecord):Promise<'CONTINUE'|'UNAUTHORIZED'>{const local=await d.getExpense(db,op.entityId);try{const {data}=await d.api.post('/sync/expenses',request(op,local));if(data.status==='CONFLICT'){await d.conflict(db,op,local,data.expense,d.createId(),d.now().toISOString());return 'CONTINUE';}await d.complete(db,op,reconcile(data.expense,local));return 'CONTINUE';}catch(error){const failure=toFailure(error);if(failure.statusCode===401){await d.releaseClaim(db,op,d.now().toISOString());return 'UNAUTHORIZED';}await d.fail(db,op,failure,isRetryableSyncError(failure),d.now());return 'CONTINUE';}}
function request(op:SyncQueueRecord,local:LocalExpenseRecord|null):{operationId:string;operationType:SyncOperationType;entityId:string;payload:Record<string,unknown>;baseVersion?:number}{let parsed:unknown;try{parsed=JSON.parse(op.payloadJson);}catch{throw {status:400,message:'Invalid queued operation.'};}if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw {status:400,message:'Invalid queued operation.'};const {baseVersion,...payload}=parsed as Record<string,unknown>;const base={operationId:op.operationId,operationType:op.operationType,entityId:op.entityId,payload};if(op.operationType==='CREATE')return base;const version=typeof baseVersion==='number'?baseVersion:local===null?undefined:local.version-1;if(!Number.isInteger(version)||version===undefined||version<1)throw {status:400,message:'Missing base version.'};return {...base,baseVersion:version};}
function reconcile(server:ServerExpense,local:LocalExpenseRecord|null):LocalExpenseRecord{if(!local)throw {status:400,message:'Local expense not found during reconciliation.'};return {id:server.id,userId:server.userId??local.userId,categoryId:server.categoryId,amountMinor:server.amountMinor,currency:server.currency,description:server.description,expenseDate:server.expenseDate.slice(0,10),createdAt:server.createdAt,updatedAt:server.updatedAt,version:server.version,deletedAt:server.deletedAt,syncStatus:'SYNCED'};}
function toFailure(error:unknown):SyncFailure{const v=error&&typeof error==='object'?error as {status?:unknown;message?:unknown;response?:{status?:unknown;data?:{message?:unknown}}}:{};const status=typeof v.status==='number'?v.status:typeof v.response?.status==='number'?v.response.status:undefined;const message=typeof v.message==='string'?v.message:typeof v.response?.data?.message==='string'?v.response.data.message:'Network request failed.';return {message:message.replace(/[\r\n]+/g,' ').slice(0,500)||'Sync request failed.',statusCode:status};}
