import { BadRequestException, ConflictException, InternalServerErrorException, NotFoundException } from '@nestjs/common';
import { createHash } from 'node:crypto';
import { Readable } from 'node:stream';
import { ReceiptsService } from './receipts.service';
import type { ReceiptStorage } from './receipt-storage.service';

const user='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',expense='33333333-3333-4333-8333-333333333333',receiptId='44444444-4444-4444-8444-444444444444';
const file=(overrides:Partial<{buffer:Buffer;mimetype:string;originalname:string;size:number}>={})=>{const buffer=overrides.buffer??Buffer.from('receipt image');return {buffer,mimetype:overrides.mimetype??'image/png',originalname:overrides.originalname??'receipt.png',size:overrides.size??buffer.length};};
describe('ReceiptsService',()=>{let prisma:{expense:{findFirst:jest.Mock};receipt:{findFirst:jest.Mock;findMany:jest.Mock;create:jest.Mock;update:jest.Mock}};let storage:ReceiptStorage;let saved:{key:string;content:Buffer}[];let removed:string[];let service:ReceiptsService;
 beforeEach(()=>{saved=[];removed=[];prisma={expense:{findFirst:jest.fn(async({where}:any)=>where.userId===user&&where.id===expense?{id:expense}:null)},receipt:{findFirst:jest.fn(async()=>null),findMany:jest.fn(async()=>[]),create:jest.fn(async({data}:any)=>({id:data.id,expenseId:data.expenseId,originalName:data.originalName,mimeType:data.mimeType,sizeBytes:data.sizeBytes,checksumSha256:data.checksumSha256,createdAt:new Date()})),update:jest.fn(async()=>({}))}};storage={save:jest.fn(async(key,content)=>{saved.push({key,content});}),open:jest.fn(async()=>Readable.from('image')),remove:jest.fn(async key=>{removed.push(key);})};service=new ReceiptsService(prisma as never,storage);});
 it('uploads only for the expense owner, calculates checksum, and returns safe metadata',async()=>{const result=await service.upload(user,expense,file());expect(result).toMatchObject({expenseId:expense,originalName:'receipt.png',mimeType:'image/png',sizeBytes:13,checksumSha256:createHash('sha256').update('receipt image').digest('hex')});expect(result).not.toHaveProperty('storageKey');expect(JSON.stringify(result)).not.toContain(saved[0]!.key);expect(saved[0]!.key).toMatch(new RegExp(`^${user}/${expense}/`));});
 it('rejects a foreign expense before reading or saving the upload',async()=>{await expect(service.upload(other,expense,file())).rejects.toBeInstanceOf(NotFoundException);expect(storage.save).not.toHaveBeenCalled();});
 it('rejects unsupported MIME types and files larger than 5 MB',async()=>{await expect(service.upload(user,expense,file({mimetype:'application/pdf'}))).rejects.toBeInstanceOf(BadRequestException);await expect(service.upload(user,expense,file({buffer:Buffer.alloc(5*1024*1024+1),size:5*1024*1024+1}))).rejects.toBeInstanceOf(BadRequestException);});
 it('rejects a duplicate checksum for the same expense',async()=>{prisma.receipt.findFirst.mockResolvedValueOnce({id:receiptId});await expect(service.upload(user,expense,file())).rejects.toBeInstanceOf(ConflictException);expect(storage.save).not.toHaveBeenCalled();});
 it('authorizes receipt reads and soft deletes metadata before safe file cleanup',async()=>{const row={id:receiptId,expenseId:expense,userId:user,storageKey:`${user}/${expense}/${receiptId}.png`,originalName:'receipt.png',mimeType:'image/png',sizeBytes:10,checksumSha256:'a'.repeat(64),createdAt:new Date(),deletedAt:null};prisma.receipt.findFirst.mockImplementation(async({where}:any)=>where.userId===user?row:null);await expect(service.open(other,expense,receiptId)).rejects.toBeInstanceOf(NotFoundException);const opened=await service.open(user,expense,receiptId);expect(opened.receipt.storageKey).toBe(row.storageKey);await service.remove(user,expense,receiptId);expect(prisma.receipt.update).toHaveBeenCalledWith(expect.objectContaining({where:{id:receiptId},data:{deletedAt:expect.any(Date)}}));expect(removed).toEqual([row.storageKey]);});
 it('rejects traversal filenames and contains storage failures',async()=>{await expect(service.upload(user,expense,file({originalname:'../private.png'}))).rejects.toBeInstanceOf(BadRequestException);expect(storage.save).not.toHaveBeenCalled();storage={save:jest.fn(async()=>{throw new Error('disk unavailable');}),open:jest.fn(),remove:jest.fn()};service=new ReceiptsService(prisma as never,storage);await expect(service.upload(user,expense,file())).rejects.toBeInstanceOf(InternalServerErrorException);});
});
