import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from 'react-native'; import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuthStore } from '../../../src/auth/auth-store';
import { getDatabase } from '../../../src/db/database';
import { listActiveExpenses, softDeleteExpense } from '../../../src/db/expense-repository';
import { listLocalCategories } from '../../../src/db/category-repository';
import type { LocalCategoryRecord, LocalExpenseRecord } from '../../../src/db/types';
import { toExpenseViewModel } from '../../../src/features/expenses/expense-presenter';
import { AppButton, Card, StateMessage } from '../../../src/ui/components';
import { colors, screen, spacing } from '../../../src/ui/theme';
export default function ExpenseListScreen():React.ReactElement {const user=useAuthStore(s=>s.user);const [expenses,setExpenses]=useState<LocalExpenseRecord[]>([]);const [categories,setCategories]=useState<LocalCategoryRecord[]>([]);const [state,setState]=useState<'loading'|'ready'|'error'>('loading');const load=useCallback(async()=>{if(!user)return;setState('loading');try{const db=await getDatabase();const [e,c]=await Promise.all([listActiveExpenses(db,user.id),listLocalCategories(db,user.id)]);setExpenses(e);setCategories(c);setState('ready');}catch{setState('error');}},[user]);useFocusEffect(useCallback(()=>{void load();},[load]));const remove=(id:string)=>Alert.alert('Delete expense?','It will be removed locally and queued for sync.',[{text:'Cancel'},{text:'Delete',style:'destructive',onPress:()=>void (async()=>{if(!user)return;try{await softDeleteExpense(await getDatabase(),{id,userId:user.id});await load();}catch{setState('error');}})()}]);return <SafeAreaView style={screen}><FlatList contentContainerStyle={styles.content} data={state==='ready'?expenses:[]} keyExtractor={x=>x.id} ListHeaderComponent={<View style={styles.top}><Text style={styles.note}>Long press an expense to delete it.</Text><AppButton label="Add expense" onPress={()=>router.push('/expenses/new')}/></View>} ListEmptyComponent={state==='loading'?<StateMessage kind="loading">Loading local expenses…</StateMessage>:state==='error'?<StateMessage kind="error">Unable to load local expenses.</StateMessage>:<StateMessage>No expenses yet. Add one online or offline.</StateMessage>} ItemSeparatorComponent={()=> <View style={{height:spacing.sm}}/>} renderItem={({item})=>{const row=toExpenseViewModel(item,categories);return <Pressable onPress={()=>router.push({pathname:'/expenses/[id]',params:{id:item.id}})} onLongPress={()=>remove(item.id)}><Card><View style={styles.row}><View><Text style={styles.name}>{row.description}</Text><Text style={styles.muted}>{row.categoryName} · {row.date}</Text><Text style={styles.muted}>{row.syncLabel}</Text></View><Text style={styles.amount}>{row.amount}</Text></View></Card></Pressable>}}/></SafeAreaView>;}
const styles=StyleSheet.create({content:{paddingVertical:spacing.md},top:{gap:spacing.sm,marginBottom:spacing.md},note:{color:colors.muted,fontSize:13},row:{flexDirection:'row',justifyContent:'space-between'},name:{color:colors.text,fontSize:16,fontWeight:'800'},muted:{color:colors.muted,fontSize:13,marginTop:3},amount:{color:colors.text,fontWeight:'800'}});
