import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuthStore } from '../../../src/auth/auth-store';
import { listLocalCategories } from '../../../src/db/category-repository';
import { getDatabase } from '../../../src/db/database';
import { insertExpense } from '../../../src/db/expense-repository';
import type { LocalCategoryRecord } from '../../../src/db/types';
import { amountToMinor, isValidExpenseDate } from '../../../src/features/expenses/expense-presenter';
import { AppButton, Card, StateMessage } from '../../../src/ui/components';
import { colors, radius, screen, spacing } from '../../../src/ui/theme';
const today=()=>new Date().toISOString().slice(0,10);
export default function CreateExpenseScreen():React.ReactElement {const user=useAuthStore(s=>s.user);const [amount,setAmount]=useState('');const [currency,setCurrency]=useState('USD');const [description,setDescription]=useState('');const [date,setDate]=useState(today());const [categories,setCategories]=useState<LocalCategoryRecord[]>([]);const [categoryId,setCategoryId]=useState<string>();const [error,setError]=useState<string|null>(null);const load=useCallback(async()=>{if(user)setCategories(await listLocalCategories(await getDatabase(),user.id));},[user]);useFocusEffect(useCallback(()=>{void load();},[load]));const save=async()=>{try{if(!user||!description.trim()||!categoryId||!isValidExpenseDate(date))throw new Error('Complete every field and use YYYY-MM-DD for the date.');const code=currency.trim().toUpperCase();if(!/^[A-Z]{3}$/.test(code))throw new Error('Currency must be a three-letter code.');await insertExpense(await getDatabase(),{userId:user.id,categoryId,amountMinor:amountToMinor(amount),currency:code,description:description.trim(),expenseDate:date});router.back();}catch(cause){setError(cause instanceof Error?cause.message:'Unable to save expense.');}};return <SafeAreaView style={screen}><ScrollView contentContainerStyle={styles.content}><TextInput style={styles.input} placeholder="Amount (e.g. 12.34)" placeholderTextColor={colors.muted} keyboardType="decimal-pad" value={amount} onChangeText={setAmount}/><TextInput style={styles.input} placeholder="Currency" placeholderTextColor={colors.muted} autoCapitalize="characters" value={currency} onChangeText={setCurrency}/><TextInput style={styles.input} placeholder="Description" placeholderTextColor={colors.muted} value={description} onChangeText={setDescription}/><TextInput style={styles.input} placeholder="YYYY-MM-DD" placeholderTextColor={colors.muted} value={date} onChangeText={setDate}/><Text style={styles.label}>Category</Text>{categories.length===0?<View><StateMessage>No categories are cached yet.</StateMessage><AppButton label="Open Categories" variant="secondary" onPress={()=>router.push('/categories')}/></View>:categories.map(c=><Card key={c.id}><AppButton label={categoryId===c.id?`✓ ${c.name}`:c.name} variant={categoryId===c.id?'primary':'secondary'} onPress={()=>setCategoryId(c.id)}/></Card>)}{error&&<Text style={styles.error}>{error}</Text>}<AppButton label="Save locally" onPress={()=>void save()}/></ScrollView></SafeAreaView>;}
const styles=StyleSheet.create({content:{paddingVertical:spacing.md,gap:spacing.sm},input:{backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,borderRadius:radius.sm,color:colors.text,padding:13},label:{color:colors.text,fontWeight:'800',marginTop:spacing.sm},error:{color:colors.danger}});
