import { StatusBar } from 'expo-status-bar';
import { Redirect } from 'expo-router';
import { useRef, useState } from 'react';
import { SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuthStore } from '../src/auth/auth-store';
import { AppButton, Card, StateMessage } from '../src/ui/components';
import { colors, radius, screen, spacing } from '../src/ui/theme';
export default function AuthScreen():React.ReactElement {const {user,isLoading,isAuthenticated,error,login,register}=useAuthStore();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('');const [submitting,setSubmitting]=useState(false);const busy=useRef(false);const submit=async(kind:'login'|'register')=>{if(busy.current)return;busy.current=true;setSubmitting(true);try{if(kind==='login')await login({email,password});else await register({name,email,password});}catch{}finally{busy.current=false;setSubmitting(false);}};if(isLoading)return <SafeAreaView style={screen}><StateMessage kind="loading">Restoring your session…</StateMessage></SafeAreaView>;if(isAuthenticated&&user)return <Redirect href="/home"/>;return <SafeAreaView style={screen}><View style={styles.container}><Text style={styles.title}>PocketLedger</Text><Text style={styles.subtitle}>Your everyday spending, kept simple.</Text><Card><View style={styles.form}><TextInput style={styles.input} placeholder="Name (for registration)" placeholderTextColor={colors.muted} value={name} onChangeText={setName}/><TextInput style={styles.input} placeholder="Email" placeholderTextColor={colors.muted} autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail}/><TextInput style={styles.input} placeholder="Password (at least 6 characters)" placeholderTextColor={colors.muted} secureTextEntry value={password} onChangeText={setPassword}/>{error&&<Text style={styles.error}>{error}</Text>}<AppButton label={submitting?'Please wait…':'Log in'} disabled={submitting} onPress={()=>void submit('login')}/><AppButton label="Create account" variant="secondary" disabled={submitting} onPress={()=>void submit('register')}/></View></Card></View><StatusBar style="light"/></SafeAreaView>;}
const styles=StyleSheet.create({container:{flex:1,justifyContent:'center',gap:spacing.md},title:{color:colors.text,fontSize:34,fontWeight:'800'},subtitle:{color:colors.muted,fontSize:16},form:{gap:spacing.sm},input:{backgroundColor:colors.background,borderWidth:1,borderColor:colors.border,color:colors.text,padding:12,borderRadius:radius.sm},error:{color:colors.danger}});
