import { api } from './client';
export interface SafeUser {id:string;name:string;email:string}
export interface GroupMember {user:SafeUser;role:'OWNER'|'MEMBER';joinedAt:string}
export interface Group {id:string;name:string;createdById:string;createdAt:string;updatedAt:string;_count?:{members:number};members?:GroupMember[]}
export interface GroupShare {id?:string;userId:string;amountMinor:number;user?:SafeUser}
export interface GroupExpense {id:string;userId:string;groupId:string;paidByUserId:string;categoryId:string;amountMinor:number;currency:string;description:string;expenseDate:string;createdAt:string;updatedAt:string;version:number;user:SafeUser;paidByUser:SafeUser;category:{id:string;name:string};shares:GroupShare[]}
export interface GroupBalance {userId:string;name:string;email:string;paidMinor:number;owedMinor:number;settledOutgoingMinor:number;settledIncomingMinor:number;netMinor:number}
export interface SettlementSuggestion {fromUserId:string;toUserId:string;amountMinor:number}
export interface Settlement {id:string;groupId:string;fromUserId:string;toUserId:string;amountMinor:number;settledAt:string;createdAt:string;fromUser:SafeUser;toUser:SafeUser}
export interface GroupExpenseInput {amountMinor:number;currency:string;description:string;expenseDate:string;categoryId:string;paidByUserId:string;shares:{userId:string;amountMinor:number}[]}
export const getGroups=async():Promise<Group[]>=>(await api.get<Group[]>('/groups')).data;
export const getGroup=async(id:string):Promise<Group>=>(await api.get<Group>(`/groups/${id}`)).data;
export const createGroup=async(name:string):Promise<Group>=>(await api.post<Group>('/groups',{name})).data;
export const addGroupMember=async(id:string,email:string):Promise<GroupMember>=>(await api.post<GroupMember>(`/groups/${id}/members`,{email})).data;
export const deleteGroupMember=async(id:string,userId:string):Promise<void>=>{await api.delete(`/groups/${id}/members/${userId}`);};
export const getGroupExpenses=async(id:string):Promise<GroupExpense[]>=>(await api.get<GroupExpense[]>(`/groups/${id}/expenses`)).data;
export const getGroupExpense=async(groupId:string,id:string):Promise<GroupExpense>=>(await api.get<GroupExpense>(`/groups/${groupId}/expenses/${id}`)).data;
export const createGroupExpense=async(groupId:string,input:GroupExpenseInput):Promise<GroupExpense>=>(await api.post<GroupExpense>(`/groups/${groupId}/expenses`,input)).data;
export const updateGroupExpense=async(groupId:string,id:string,input:GroupExpenseInput):Promise<GroupExpense>=>(await api.patch<GroupExpense>(`/groups/${groupId}/expenses/${id}`,input)).data;
export const deleteGroupExpense=async(groupId:string,id:string):Promise<void>=>{await api.delete(`/groups/${groupId}/expenses/${id}`);};
export const getGroupBalances=async(id:string):Promise<GroupBalance[]>=>(await api.get<GroupBalance[]>(`/groups/${id}/balances`)).data;
export const getSettlementSuggestions=async(id:string):Promise<SettlementSuggestion[]>=>(await api.get<SettlementSuggestion[]>(`/groups/${id}/settlement-suggestions`)).data;
export const getSettlements=async(id:string):Promise<Settlement[]>=>(await api.get<Settlement[]>(`/groups/${id}/settlements`)).data;
export const createSettlement=async(groupId:string,toUserId:string,amountMinor:number):Promise<Settlement>=>(await api.post<Settlement>(`/groups/${groupId}/settlements`,{toUserId,amountMinor})).data;
export const deleteSettlement=async(groupId:string,id:string):Promise<void>=>{await api.delete(`/groups/${groupId}/settlements/${id}`);};
