import NetInfo from '@react-native-community/netinfo';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native'; import { SafeAreaView } from 'react-native-safe-area-context';
import { getGroups, type Group } from '../../../src/api/group-service';
import { AppButton, Card, OfflineNotice, StateMessage } from '../../../src/ui/components';
import { colors, screen, spacing } from '../../../src/ui/theme';
export default function GroupsScreen():React.ReactElement {const net=NetInfo.useNetInfo();const offline=net.isConnected===false||net.isInternetReachable===false;const [groups,setGroups]=useState<Group[]>([]);const [state,setState]=useState<'loading'|'ready'|'error'>('loading');const load=useCallback(async()=>{if(offline){setState('ready');return;}setState('loading');try{setGroups(await getGroups());setState('ready');}catch{setState('error');}},[offline]);useFocusEffect(useCallback(()=>{void load();},[load]));return <SafeAreaView style={screen}><FlatList data={groups} contentContainerStyle={styles.content} keyExtractor={x=>x.id} ListHeaderComponent={<View style={styles.head}>{offline&&<OfflineNotice/>}<AppButton label="Create group" disabled={offline} onPress={()=>router.push('/groups/new')}/>{offline&&<Text style={styles.hint}>Groups are online-only; synchronization is not implemented yet.</Text>}</View>} ListEmptyComponent={state==='loading'?<StateMessage kind="loading">Loading groups…</StateMessage>:state==='error'?<StateMessage kind="error">Unable to load groups.</StateMessage>:offline?<StateMessage kind="offline">Connect to view your groups.</StateMessage>:<StateMessage>No groups yet. Create one to split expenses.</StateMessage>} ItemSeparatorComponent={()=> <View style={{height:spacing.sm}}/>} renderItem={({item})=><Pressable onPress={()=>router.push({pathname:'/groups/[id]',params:{id:item.id}})}><Card><Text style={styles.name}>{item.name}</Text><Text style={styles.muted}>{item._count?.members??0} member{item._count?.members===1?'':'s'}</Text></Card></Pressable>}/></SafeAreaView>;}
const styles=StyleSheet.create({content:{paddingVertical:spacing.md},head:{gap:spacing.sm,marginBottom:spacing.md},hint:{color:colors.muted,fontSize:13},name:{color:colors.text,fontSize:17,fontWeight:'800'},muted:{color:colors.muted,marginTop:4}});
