import type { SQLiteDatabase } from 'expo-sqlite';
import { enqueueSyncOperation } from './sync-queue-repository';
import type { LocalExpenseRecord, SyncConflictRecord } from './types';

type ServerExpenseSnapshot={id:string;userId?:string;categoryId:string|null;amountMinor:number;currency:string;description:string;expenseDate:string;createdAt:string;updatedAt:string;version:number;deletedAt:string|null;};
type LocalConflictPayload={operation:unknown;expense:LocalExpenseRecord|null;};
export interface ExpenseConflictSnapshot { local:LocalExpenseRecord; server:ServerExpenseSnapshot; }
export const createConflictResolutionOperationId=()=>globalThis.crypto.randomUUID();

const expenseConflictSelect=`SELECT c.* FROM sync_conflicts c INNER JOIN expenses e ON e.id=c.entityId WHERE c.entityType='expense' AND e.userId=?`;

export const listUnresolvedExpenseConflicts=(db:SQLiteDatabase,userId:string)=>db.getAllAsync<SyncConflictRecord>(`${expenseConflictSelect} AND c.resolvedAt IS NULL ORDER BY c.createdAt DESC`,userId);
export const countUnresolvedExpenseConflicts=async(db:SQLiteDatabase,userId:string):Promise<number>=>((await db.getFirstAsync<{count:number}>(`${expenseConflictSelect.replace('SELECT c.*','SELECT COUNT(*) AS count')} AND c.resolvedAt IS NULL`,userId))?.count??0);
export const getExpenseConflictById=(db:SQLiteDatabase,userId:string,id:string)=>db.getFirstAsync<SyncConflictRecord>(`${expenseConflictSelect} AND c.id=?`,userId,id);

export async function markExpenseConflictResolved(db:SQLiteDatabase,userId:string,id:string,resolvedAt:string=new Date().toISOString()):Promise<void>{const result=await db.runAsync(`UPDATE sync_conflicts SET resolvedAt=? WHERE id=? AND resolvedAt IS NULL AND entityType='expense' AND EXISTS (SELECT 1 FROM expenses e WHERE e.id=sync_conflicts.entityId AND e.userId=?)`,resolvedAt,id,userId);if(result.changes!==1)throw new Error('Expense conflict not found.');}

export function expenseConflictSnapshot(conflict:SyncConflictRecord):ExpenseConflictSnapshot{const local=parseLocal(conflict.localPayloadJson),server=parseServer(conflict.serverPayloadJson);if(!local)throw new Error('Expense conflict has no local snapshot.');return {local,server};}

export async function resolveExpenseConflictWithServer(db:SQLiteDatabase,userId:string,id:string,resolvedAt:string=new Date().toISOString()):Promise<void>{await inTransaction(db,async tx=>{const conflict=await getExpenseConflictById(tx,userId,id);if(!conflict||conflict.resolvedAt!==null)throw new Error('Expense conflict not found.');const {server}=expenseConflictSnapshot(conflict);const result=await tx.runAsync('UPDATE expenses SET categoryId=?,amountMinor=?,currency=?,description=?,expenseDate=?,createdAt=?,updatedAt=?,version=?,deletedAt=?,syncStatus=? WHERE id=? AND userId=?',server.categoryId,server.amountMinor,server.currency,server.description,server.expenseDate.slice(0,10),server.createdAt,server.updatedAt,server.version,server.deletedAt,'SYNCED',server.id,userId);if(result.changes!==1)throw new Error('Local expense not found.');await markExpenseConflictResolved(tx,userId,id,resolvedAt);});}

export async function resolveExpenseConflictWithLocal(db:SQLiteDatabase,userId:string,id:string,operationId:string=createConflictResolutionOperationId(),timestamp:string=new Date().toISOString()):Promise<void>{await inTransaction(db,async tx=>{const conflict=await getExpenseConflictById(tx,userId,id);if(!conflict||conflict.resolvedAt!==null)throw new Error('Expense conflict not found.');if(operationId===conflict.operationId)throw new Error('Replacement operation ID must be new.');const {local,server}=expenseConflictSnapshot(conflict);if(local.userId!==userId||local.id!==server.id)throw new Error('Expense conflict user scope mismatch.');const replacement:{id:string;userId:string;categoryId:string|null;amountMinor:number;currency:string;description:string;expenseDate:string;baseVersion:number}={id:local.id,userId,categoryId:local.categoryId,amountMinor:local.amountMinor,currency:local.currency,description:local.description,expenseDate:local.expenseDate,baseVersion:server.version};const result=await tx.runAsync('UPDATE expenses SET categoryId=?,amountMinor=?,currency=?,description=?,expenseDate=?,updatedAt=?,version=?,deletedAt=?,syncStatus=? WHERE id=? AND userId=?',local.categoryId,local.amountMinor,local.currency,local.description,local.expenseDate,timestamp,server.version+1,null,'PENDING',local.id,userId);if(result.changes!==1)throw new Error('Local expense not found.');await enqueueSyncOperation(tx,{operationId,entityType:'expense',entityId:local.id,operationType:'UPDATE',payload:replacement,timestamp});await markExpenseConflictResolved(tx,userId,id,timestamp);});}

function parseLocal(payload:string):LocalExpenseRecord|null{try{const value=JSON.parse(payload) as LocalConflictPayload;return value?.expense??null;}catch{throw new Error('Expense conflict has an invalid local snapshot.');}}
function parseServer(payload:string):ServerExpenseSnapshot{try{const value=JSON.parse(payload) as Partial<ServerExpenseSnapshot>;if(!value||typeof value.id!=='string'||typeof value.version!=='number'||typeof value.amountMinor!=='number'||typeof value.currency!=='string'||typeof value.description!=='string'||typeof value.expenseDate!=='string'||typeof value.createdAt!=='string'||typeof value.updatedAt!=='string')throw new Error();return {id:value.id,userId:value.userId,categoryId:value.categoryId??null,amountMinor:value.amountMinor,currency:value.currency,description:value.description,expenseDate:value.expenseDate,createdAt:value.createdAt,updatedAt:value.updatedAt,version:value.version,deletedAt:value.deletedAt??null};}catch{throw new Error('Expense conflict has an invalid server snapshot.');}}
async function inTransaction<T>(db:SQLiteDatabase,work:(transaction:SQLiteDatabase)=>Promise<T>):Promise<T>{let result:T|undefined;await db.withTransactionAsync(async()=>{result=await work(db);});return result as T;}
