import assert from 'node:assert/strict';
import test from 'node:test';
import { countUnresolvedExpenseConflicts,createConflictResolutionOperationId,listUnresolvedExpenseConflicts,resolveExpenseConflictWithLocal,resolveExpenseConflictWithServer } from './conflict-repository';
import type { LocalExpenseRecord,SyncConflictRecord } from './types';

const local:LocalExpenseRecord={id:'expense',userId:'user-a',categoryId:'local-category',amountMinor:1234,currency:'PKR',description:'Local dinner',expenseDate:'2026-09-01',createdAt:'2026-09-01T00:00:00.000Z',updatedAt:'2026-09-01T00:00:00.000Z',version:4,deletedAt:null,syncStatus:'PENDING'};
const server={id:'expense',userId:'user-a',categoryId:'server-category',amountMinor:1500,currency:'USD',description:'Server dinner',expenseDate:'2026-09-02T00:00:00.000Z',createdAt:'2026-08-01T00:00:00.000Z',updatedAt:'2026-09-02T00:00:00.000Z',version:7,deletedAt:null};
const conflict:SyncConflictRecord={id:'conflict',operationId:'conflicted-operation',entityType:'expense',entityId:'expense',localPayloadJson:JSON.stringify({operation:{baseVersion:3},expense:local}),serverPayloadJson:JSON.stringify(server),createdAt:'2026-09-02T00:00:00.000Z',resolvedAt:null};
function transactionDb(){const calls:unknown[][]=[];const db={getFirstAsync:async(...args:unknown[])=>{const sql=args[0] as string;if(sql.includes('COUNT(*)'))return {count:2};return conflict;},getAllAsync:async()=>[conflict],runAsync:async(...args:unknown[])=>{calls.push(args);return {changes:1};},withTransactionAsync:async(work:()=>Promise<void>)=>work()};return {db,calls};}

test('lists and counts only unresolved conflicts scoped to the current expense owner',async()=>{let query:unknown[]=[];const db={getAllAsync:async(...args:unknown[])=>{query=args;return [] as SyncConflictRecord[];},getFirstAsync:async()=>({count:3})};await listUnresolvedExpenseConflicts(db as never,'user-a');assert.match(query[0] as string,/INNER JOIN expenses/);assert.match(query[0] as string,/e.userId=\?/);assert.deepEqual(query.slice(1),['user-a']);assert.equal(await countUnresolvedExpenseConflicts(db as never,'user-a'),3);});
test('keep server replaces the local record and resolves history without queueing',async()=>{const {db,calls}=transactionDb();await resolveExpenseConflictWithServer(db as never,'user-a','conflict','2026-09-03T00:00:00.000Z');assert.equal(calls.length,2);assert.match(calls[0]?.[0] as string,/UPDATE expenses SET/);assert.equal(calls[0]?.[8],7);assert.match(calls[1]?.[0] as string,/UPDATE sync_conflicts SET resolvedAt/);assert.doesNotMatch(calls.map(call=>call[0]).join(' '),/INSERT INTO sync_queue/);});
test('keep local writes the local version, a new update operation, then resolves the conflict atomically',async()=>{const {db,calls}=transactionDb();await resolveExpenseConflictWithLocal(db as never,'user-a','conflict','replacement-operation','2026-09-03T00:00:00.000Z');assert.equal(calls.length,3);assert.match(calls[0]?.[0] as string,/UPDATE expenses SET/);assert.equal(calls[0]?.[7],8);assert.match(calls[1]?.[0] as string,/INSERT INTO sync_queue/);assert.equal(calls[1]?.[1],'replacement-operation');const payload=JSON.parse(calls[1]?.[5] as string);assert.equal(payload.baseVersion,7);assert.equal(payload.description,'Local dinner');assert.match(calls[2]?.[0] as string,/UPDATE sync_conflicts SET resolvedAt/);assert.equal(calls.filter(call=>(call[0] as string).includes('INSERT INTO sync_queue')).length,1);});
test('keep local never reuses the conflicted operation ID',async()=>{const {db}=transactionDb();await assert.rejects(resolveExpenseConflictWithLocal(db as never,'user-a','conflict','conflicted-operation'),/must be new/);});
test('generates a new UUID for a replacement operation',()=>{const id=createConflictResolutionOperationId();assert.notEqual(id,conflict.operationId);assert.match(id,/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i);});
