import type { SQLiteDatabase } from 'expo-sqlite';
import { runTransaction } from './database';
import { enqueueSyncOperation } from './sync-queue-repository';
import type { LocalExpenseRecord, SyncOperationType } from './types';
export interface CreateLocalExpenseInput { userId:string; categoryId?:string|null; amountMinor:number; currency:string; description:string; expenseDate:string; }
export interface UpdateLocalExpenseInput { id:string; userId:string; amountMinor?:number; currency?:string; description?:string; expenseDate?:string; categoryId?:string|null; }
const now=()=>new Date().toISOString(); export const createClientUuid=()=>globalThis.crypto.randomUUID();
export async function insertExpense(db:SQLiteDatabase,input:CreateLocalExpenseInput):Promise<LocalExpenseRecord>{const timestamp=now();const e:LocalExpenseRecord={id:createClientUuid(),userId:input.userId,categoryId:input.categoryId??null,amountMinor:input.amountMinor,currency:input.currency,description:input.description,expenseDate:input.expenseDate,createdAt:timestamp,updatedAt:timestamp,version:1,deletedAt:null,syncStatus:'PENDING'};await runTransaction(db,async tx=>{await tx.runAsync('INSERT INTO expenses VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',e.id,e.userId,e.categoryId,e.amountMinor,e.currency,e.description,e.expenseDate,e.createdAt,e.updatedAt,e.version,e.deletedAt,e.syncStatus);await queue(tx,e.id,'CREATE',e,timestamp);});return e;}
export const listActiveExpenses=(db:SQLiteDatabase,userId:string)=>db.getAllAsync<LocalExpenseRecord>('SELECT * FROM expenses WHERE userId=? AND deletedAt IS NULL ORDER BY expenseDate DESC,createdAt DESC',userId);
export const getExpenseById=(db:SQLiteDatabase,id:string,userId?:string)=>userId===undefined?db.getFirstAsync<LocalExpenseRecord>('SELECT * FROM expenses WHERE id=?',id):db.getFirstAsync<LocalExpenseRecord>('SELECT * FROM expenses WHERE id=? AND userId=?',id,userId);
export async function updateExpense(db:SQLiteDatabase,input:UpdateLocalExpenseInput){const timestamp=now();await runTransaction(db,async tx=>{const existing=await tx.getFirstAsync<LocalExpenseRecord>('SELECT * FROM expenses WHERE id=? AND userId=? AND deletedAt IS NULL',input.id,input.userId);if(!existing)throw new Error('Local expense not found.');const r=await tx.runAsync('UPDATE expenses SET amountMinor=COALESCE(?,amountMinor),currency=COALESCE(?,currency),description=COALESCE(?,description),expenseDate=COALESCE(?,expenseDate),categoryId=CASE WHEN ? THEN ? ELSE categoryId END,updatedAt=?,version=version+1,syncStatus=? WHERE id=? AND userId=? AND deletedAt IS NULL',input.amountMinor??null,input.currency??null,input.description??null,input.expenseDate??null,input.categoryId!==undefined?1:0,input.categoryId??null,timestamp,'PENDING',input.id,input.userId);if(r.changes!==1)throw new Error('Local expense not found.');await queue(tx,input.id,'UPDATE',{...input,baseVersion:existing.version},timestamp);});}
export async function softDeleteExpense(db:SQLiteDatabase,input:{id:string;userId:string}){const timestamp=now();await runTransaction(db,async tx=>{const existing=await tx.getFirstAsync<LocalExpenseRecord>('SELECT * FROM expenses WHERE id=? AND userId=? AND deletedAt IS NULL',input.id,input.userId);if(!existing)throw new Error('Local expense not found.');const r=await tx.runAsync('UPDATE expenses SET deletedAt=?,updatedAt=?,version=version+1,syncStatus=? WHERE id=? AND userId=? AND deletedAt IS NULL',timestamp,timestamp,'PENDING',input.id,input.userId);if(r.changes!==1)throw new Error('Local expense not found.');await queue(tx,input.id,'DELETE',{...input,deletedAt:timestamp,baseVersion:existing.version},timestamp);});}
async function queue(db:SQLiteDatabase,id:string,type:SyncOperationType,payload:unknown,timestamp:string){await enqueueSyncOperation(db,{operationId:createClientUuid(),entityType:'expense',entityId:id,operationType:type,payload,timestamp});}
