import type { Group,GroupBalance,GroupExpense,GroupMember,Settlement,SettlementSuggestion } from '../api/group-service';
import type { SQLiteDatabase } from 'expo-sqlite';
import { runTransaction } from './database';
const parse=<T>(value:string):T=>JSON.parse(value) as T;
export const listCachedGroups=(db:SQLiteDatabase,userId:string)=>db.getAllAsync<{payloadJson:string}>('SELECT payloadJson FROM cached_groups WHERE userId=? ORDER BY updatedAt DESC',userId).then(rows=>rows.map(row=>parse<Group>(row.payloadJson)));
export const getCachedGroup=async(db:SQLiteDatabase,userId:string,id:string)=>{const row=await db.getFirstAsync<{payloadJson:string}>('SELECT payloadJson FROM cached_groups WHERE id=? AND userId=?',id,userId);return row?parse<Group>(row.payloadJson):null;};
export async function replaceCachedGroups(db:SQLiteDatabase,userId:string,groups:Group[]){const now=new Date().toISOString();await runTransaction(db,async tx=>{await tx.runAsync('DELETE FROM cached_groups WHERE userId=?',userId);for(const group of groups)await tx.runAsync('INSERT INTO cached_groups (id,userId,payloadJson,updatedAt) VALUES (?,?,?,?)',group.id,userId,JSON.stringify(group),now);});}
export async function replaceCachedGroupDetail(db:SQLiteDatabase,userId:string,group:Group,expenses:GroupExpense[],balances:GroupBalance[],suggestions:SettlementSuggestion[],settlements:Settlement[]){const now=new Date().toISOString(),replace=async(table:string)=>tx.runAsync(`DELETE FROM ${table} WHERE groupId=? AND userId=?`,group.id,userId);let tx!:SQLiteDatabase;await runTransaction(db,async transaction=>{tx=transaction;await tx.runAsync('INSERT OR REPLACE INTO cached_groups (id,userId,payloadJson,updatedAt) VALUES (?,?,?,?)',group.id,userId,JSON.stringify(group),now);for(const table of ['cached_group_members','cached_group_expenses','cached_group_shares','cached_settlements','cached_group_balances','cached_settlement_suggestions'])await replace(table);for(const member of group.members??[])await tx.runAsync('INSERT INTO cached_group_members VALUES (?,?,?,?)',group.id,userId,member.user.id,JSON.stringify(member));for(const expense of expenses){await tx.runAsync('INSERT INTO cached_group_expenses VALUES (?,?,?,?,?)',expense.id,group.id,userId,JSON.stringify(expense),now);for(const share of expense.shares)await tx.runAsync('INSERT INTO cached_group_shares VALUES (?,?,?,?)',expense.id,userId,share.userId,JSON.stringify(share));}for(const settlement of settlements)await tx.runAsync('INSERT INTO cached_settlements VALUES (?,?,?,?)',settlement.id,group.id,userId,JSON.stringify(settlement));for(const balance of balances)await tx.runAsync('INSERT INTO cached_group_balances VALUES (?,?,?,?)',group.id,userId,balance.userId,JSON.stringify(balance));for(const [position,suggestion] of suggestions.entries())await tx.runAsync('INSERT INTO cached_settlement_suggestions VALUES (?,?,?,?)',group.id,userId,position,JSON.stringify(suggestion));await tx.runAsync('INSERT OR REPLACE INTO group_cache_metadata VALUES (?,?,?)',group.id,userId,now);});}
export async function getCachedGroupDetail(db:SQLiteDatabase,userId:string,groupId:string){const group=await getCachedGroup(db,userId,groupId);const read=async<T>(table:string)=>{const rows=await db.getAllAsync<{payloadJson:string}>(`SELECT payloadJson FROM ${table} WHERE groupId=? AND userId=?`,groupId,userId);return rows.map(row=>parse<T>(row.payloadJson));};return {group,expenses:await read<GroupExpense>('cached_group_expenses'),balances:await read<GroupBalance>('cached_group_balances'),suggestions:await read<SettlementSuggestion>('cached_settlement_suggestions'),settlements:await read<Settlement>('cached_settlements')};}
