import type { SQLiteDatabase } from 'expo-sqlite';
import type { LocalExpenseReceiptRecord } from './types';
import { createClientUuid } from './expense-repository';
const now=()=>new Date().toISOString();
export async function addLocalReceipt(db:SQLiteDatabase,input:{userId:string;expenseId:string;localUri:string}):Promise<LocalExpenseReceiptRecord>{const expense=await db.getFirstAsync<{id:string}>('SELECT id FROM expenses WHERE id=? AND userId=? AND deletedAt IS NULL',input.expenseId,input.userId);if(!expense)throw new Error('Local expense not found.');const timestamp=now(),receipt:LocalExpenseReceiptRecord={id:createClientUuid(),userId:input.userId,expenseId:input.expenseId,localUri:input.localUri,capturedAt:timestamp,deletedAt:null,syncStatus:'PENDING',remoteReceiptId:null,attempts:0,lastError:null,updatedAt:timestamp};await db.runAsync('INSERT INTO expense_receipts (id,userId,expenseId,localUri,capturedAt,deletedAt,syncStatus,remoteReceiptId,attempts,lastError,updatedAt) VALUES (?,?,?,?,?,?,?,?,?,?,?)',receipt.id,receipt.userId,receipt.expenseId,receipt.localUri,receipt.capturedAt,null,receipt.syncStatus,null,0,null,timestamp);return receipt;}
export const listLocalReceipts=(db:SQLiteDatabase,userId:string,expenseId:string)=>db.getAllAsync<LocalExpenseReceiptRecord>('SELECT * FROM expense_receipts WHERE userId=? AND expenseId=? AND deletedAt IS NULL ORDER BY capturedAt DESC',userId,expenseId);
export const listPendingReceiptUploads=(db:SQLiteDatabase,userId:string,limit=1)=>db.getAllAsync<LocalExpenseReceiptRecord>('SELECT r.* FROM expense_receipts r INNER JOIN expenses e ON e.id=r.expenseId WHERE r.userId=? AND r.deletedAt IS NULL AND r.syncStatus=? AND e.userId=r.userId AND e.deletedAt IS NULL AND e.syncStatus=? ORDER BY r.capturedAt ASC LIMIT ?',userId,'PENDING','SYNCED',limit);
export async function claimReceiptUpload(db:SQLiteDatabase,userId:string,id:string,timestamp:string=now()){const result=await db.runAsync('UPDATE expense_receipts SET syncStatus=?,updatedAt=? WHERE id=? AND userId=? AND deletedAt IS NULL AND syncStatus=?','UPLOADING',timestamp,id,userId,'PENDING');return result.changes===1;}
export async function recoverStaleReceiptUploads(db:SQLiteDatabase,userId:string,staleBefore:string,timestamp:string=now()){const result=await db.runAsync('UPDATE expense_receipts SET syncStatus=?,updatedAt=? WHERE userId=? AND deletedAt IS NULL AND syncStatus=? AND updatedAt<?','PENDING',timestamp,userId,'UPLOADING',staleBefore);return result.changes;}
export async function markReceiptUploadSuccess(db:SQLiteDatabase,userId:string,id:string,remoteReceiptId:string,timestamp:string=now()){const result=await db.runAsync('UPDATE expense_receipts SET syncStatus=?,remoteReceiptId=?,lastError=?,updatedAt=? WHERE id=? AND userId=? AND syncStatus=?','SYNCED',remoteReceiptId,null,timestamp,id,userId,'UPLOADING');return result.changes===1;}
export async function markReceiptUploadFailure(db:SQLiteDatabase,userId:string,id:string,message:string,retryable:boolean,timestamp:string=now()){const result=await db.runAsync('UPDATE expense_receipts SET syncStatus=?,attempts=attempts+1,lastError=?,updatedAt=? WHERE id=? AND userId=? AND syncStatus=?',retryable?'PENDING':'FAILED',message.slice(0,500),timestamp,id,userId,'UPLOADING');return result.changes===1;}
export async function retryReceiptUpload(db:SQLiteDatabase,userId:string,id:string,timestamp:string=now()){const result=await db.runAsync('UPDATE expense_receipts SET syncStatus=?,attempts=?,lastError=?,updatedAt=? WHERE id=? AND userId=? AND deletedAt IS NULL AND syncStatus=?','PENDING',0,null,timestamp,id,userId,'FAILED');if(result.changes!==1)throw new Error('Receipt not found.');}
export async function deleteLocalReceipt(db:SQLiteDatabase,input:{userId:string;receiptId:string}){const timestamp=now(),result=await db.runAsync('UPDATE expense_receipts SET deletedAt=?,updatedAt=? WHERE id=? AND userId=? AND deletedAt IS NULL',timestamp,timestamp,input.receiptId,input.userId);if(result.changes!==1)throw new Error('Receipt not found.');}
