import NetInfo from '@react-native-community/netinfo';
import { Ionicons } from '@expo/vector-icons';
import { router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from 'react-native'; import { SafeAreaView } from 'react-native-safe-area-context';
import { deleteBudget } from '../../../src/api/budget-service'; import { useAuthStore } from '../../../src/auth/auth-store';
import { listLocalBudgets, removeLocalBudget, type LocalBudgetWithCategory } from '../../../src/db/budget-repository'; import { getDatabase } from '../../../src/db/database'; import { listActiveExpenses } from '../../../src/db/expense-repository'; import type { LocalExpenseRecord } from '../../../src/db/types';
import { budgetMutationError } from '../../../src/features/budgets/budget-errors'; import { budgetProgress, isOverBudget, remainingAmount, spendingForBudget } from '../../../src/features/budgets/budget-logic'; import { formatMinor } from '../../../src/features/currency/amount'; import { usePreferencesStore } from '../../../src/preferences/preferences-store'; import { AppButton, Card, IconAction, OfflineNotice, StateMessage } from '../../../src/ui/components'; import { colors, screen, spacing } from '../../../src/ui/theme';
const today = new Date();
export default function BudgetsScreen(): React.ReactElement {
  const user = useAuthStore(s => s.user); const preferences = usePreferencesStore(s => s.preferences); const net = NetInfo.useNetInfo(); const offline = net.isConnected === false || net.isInternetReachable === false;
  const [month, setMonth] = useState(today.getMonth() + 1); const [year, setYear] = useState(today.getFullYear()); const [budgets, setBudgets] = useState<LocalBudgetWithCategory[]>([]); const [expenses, setExpenses] = useState<LocalExpenseRecord[]>([]); const [state, setState] = useState<'loading' | 'ready' | 'error'>('loading'); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!user) return; setState('loading'); try { const db = await getDatabase(); const [b, e] = await Promise.all([listLocalBudgets(db, user.id, { month, year }), listActiveExpenses(db, user.id)]); setBudgets(b); setExpenses(e); setState('ready'); } catch { setState('error'); } }, [user, month, year]); useFocusEffect(useCallback(() => { void load(); }, [load]));
  const previous = () => month === 1 ? (setMonth(12), setYear(v => v - 1)) : setMonth(v => v - 1); const next = () => month === 12 ? (setMonth(1), setYear(v => v + 1)) : setMonth(v => v + 1);
  const remove = (item: LocalBudgetWithCategory) => Alert.alert('Delete budget?', 'This removes the cached budget after the server confirms deletion.', [{ text: 'Cancel' }, { text: 'Delete', style: 'destructive', onPress: () => void (async () => { try { await deleteBudget(item.id); if (user) await removeLocalBudget(await getDatabase(), user.id, item.id); await load(); } catch (cause) { setError(budgetMutationError(cause)); } })() }]);
  const label = new Date(year, month - 1, 1).toLocaleDateString('en-US', { month: 'long', year: 'numeric' }); const money = (minor: number) => formatMinor(minor, preferences?.defaultCurrency ?? 'PKR', preferences?.showDecimalPlaces ?? true);
  return <SafeAreaView style={screen}><FlatList contentContainerStyle={styles.content} data={state === 'ready' ? budgets : []} keyExtractor={x => x.id} ListHeaderComponent={<View style={styles.head}>{offline && <OfflineNotice />}<View style={styles.period}><Pressable accessibilityRole="button" accessibilityLabel="Previous month" hitSlop={8} onPress={previous}><Ionicons name="chevron-back" size={26} color={colors.accent} /></Pressable><Text style={styles.periodText}>{label}</Text><Pressable accessibilityRole="button" accessibilityLabel="Next month" hitSlop={8} onPress={next}><Ionicons name="chevron-forward" size={26} color={colors.accent} /></Pressable></View><AppButton label="Add budget" disabled={offline} onPress={() => router.push({ pathname: '/budgets/new', params: { month: String(month), year: String(year) } })} />{offline && <Text style={styles.hint}>Connect to add, edit, or delete budgets.</Text>}{error && <Text accessibilityRole="alert" style={styles.error}>{error}</Text>}</View>} ListEmptyComponent={state === 'loading' ? <StateMessage kind="loading">Loading cached budgets…</StateMessage> : state === 'error' ? <StateMessage kind="error">Unable to load local budgets.</StateMessage> : offline ? <StateMessage kind="offline">No cached budgets are available for this month.</StateMessage> : <StateMessage>No budgets for this month. Add an overall or category budget.</StateMessage>} ItemSeparatorComponent={() => <View style={{ height: spacing.sm }} />} renderItem={({ item }) => { const spent = spendingForBudget(item, expenses), over = isOverBudget(item.amountMinor, spent), progress = budgetProgress(item.amountMinor, spent), remaining = remainingAmount(item.amountMinor, spent); return <Card><View style={styles.row}><View style={styles.detail}><Text style={styles.name}>{item.categoryName ?? 'Overall budget'}</Text><Text style={styles.muted}>{money(spent)} spent of {money(item.amountMinor)}</Text></View><View style={styles.actions}><IconAction icon="pencil" label="Edit budget" disabled={offline} onPress={() => router.push({ pathname: '/budgets/[id]', params: { id: item.id } })} /><IconAction icon="trash-outline" label="Delete budget" tone="danger" disabled={offline} onPress={() => remove(item)} /></View></View><View style={styles.track}><View style={[styles.bar, { width: `${Math.min(progress, 100)}%` }, over && styles.over]} /></View><Text style={[styles.remaining, over && styles.overText]}>{over ? `${money(Math.abs(remaining))} over budget` : `${money(remaining)} remaining`} · {progress}%</Text></Card>; }} /></SafeAreaView>;
}
const styles = StyleSheet.create({ content: { paddingVertical: spacing.md }, head: { gap: spacing.sm, marginBottom: spacing.md }, period: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, periodText: { color: colors.text, fontSize: 20, fontWeight: '800' }, hint: { color: colors.muted, fontSize: 13 }, error: { color: colors.danger }, row: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.sm, justifyContent: 'space-between' }, detail: { flex: 1 }, name: { color: colors.text, fontSize: 16, fontWeight: '800' }, muted: { color: colors.muted, fontSize: 13, marginTop: 3 }, actions: { flexDirection: 'row', gap: spacing.xs }, track: { backgroundColor: colors.border, borderRadius: 8, height: 8, marginTop: spacing.md, overflow: 'hidden' }, bar: { backgroundColor: colors.accent, height: '100%' }, over: { backgroundColor: colors.danger }, remaining: { color: colors.muted, fontSize: 13, marginTop: spacing.sm }, overText: { color: colors.danger } });
