import NetInfo from '@react-native-community/netinfo';
import { Redirect, router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Alert, Button, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { useAuthStore } from '../../src/auth/auth-store';
import { listLocalCategories } from '../../src/db/category-repository';
import { getDatabase } from '../../src/db/database';
import { listActiveExpenses, softDeleteExpense } from '../../src/db/expense-repository';
import type { LocalCategoryRecord, LocalExpenseRecord } from '../../src/db/types';
import { toExpenseViewModel } from '../../src/features/expenses/expense-presenter';
import { isSyncRunActive } from '../../src/sync/sync-worker';

export default function ExpenseListScreen():React.ReactElement{const user=useAuthStore(state=>state.user);const authenticated=useAuthStore(state=>state.isAuthenticated);const net=NetInfo.useNetInfo();const [expenses,setExpenses]=useState<LocalExpenseRecord[]>([]);const [categories,setCategories]=useState<LocalCategoryRecord[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const load=useCallback(async()=>{if(!user)return;setLoading(true);try{const db=await getDatabase();const [localExpenses,localCategories]=await Promise.all([listActiveExpenses(db,user.id),listLocalCategories(db,user.id)]);setExpenses(localExpenses);setCategories(localCategories);setError(null);}catch{setError('Unable to load local expenses.');}finally{setLoading(false);}},[user]);useFocusEffect(useCallback(()=>{void load();},[load]));if(!authenticated||!user)return <Redirect href="/"/>;const offline=net.isConnected===false||net.isInternetReachable===false;const remove=(id:string)=>Alert.alert('Delete expense?','This will remove it from your local list and queue the deletion for sync.',[{text:'Cancel',style:'cancel'},{text:'Delete',style:'destructive',onPress:()=>void (async()=>{try{const db=await getDatabase();await softDeleteExpense(db,{id,userId:user.id});await load();}catch{setError('Unable to delete this expense.');}})()}]);return <View style={styles.container}>{offline&&<Text style={styles.offline}>Offline — changes will sync later.</Text>}<View style={styles.header}><Text style={styles.title}>Expenses</Text><Button title="Add" onPress={()=>router.push('/expenses/new')}/></View>{loading?<Text>Loading local expenses…</Text>:error?<Text style={styles.error}>{error}</Text>:<FlatList data={expenses} keyExtractor={item=>item.id} ListEmptyComponent={<Text style={styles.empty}>No expenses yet. Add one while online or offline.</Text>} renderItem={({item})=>{const view=toExpenseViewModel(item,categories,isSyncRunActive());return <Pressable style={styles.item} onPress={()=>router.push({pathname:'/expenses/[id]',params:{id:item.id}})} onLongPress={()=>remove(item.id)}><View><Text style={styles.description}>{view.description}</Text><Text>{view.categoryName} · {view.date}</Text><Text style={styles.status}>{view.syncLabel}</Text></View><Text style={styles.amount}>{view.amount}</Text></Pressable>}}/>}</View>;}
const styles=StyleSheet.create({container:{flex:1,padding:20,backgroundColor:'#fff'},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:16},title:{fontSize:28,fontWeight:'700'},offline:{backgroundColor:'#fff3cd',padding:10,color:'#6b4f00',marginBottom:12},item:{paddingVertical:16,borderBottomWidth:1,borderColor:'#e5e7eb',flexDirection:'row',justifyContent:'space-between'},description:{fontSize:17,fontWeight:'600'},amount:{fontSize:16,fontWeight:'700'},status:{fontSize:12,color:'#526075',marginTop:4},empty:{marginTop:40,textAlign:'center',color:'#526075'},error:{color:'#b42318'}});
