import { Redirect, router, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Button, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useAuthStore } from '../../src/auth/auth-store';
import { listLocalCategories } from '../../src/db/category-repository';
import { getDatabase } from '../../src/db/database';
import { insertExpense } from '../../src/db/expense-repository';
import type { LocalCategoryRecord } from '../../src/db/types';
import { amountToMinor, isValidExpenseDate } from '../../src/features/expenses/expense-presenter';
const today=()=>new Date().toISOString().slice(0,10);
export default function CreateExpenseScreen():React.ReactElement{const user=useAuthStore(state=>state.user);const authenticated=useAuthStore(state=>state.isAuthenticated);const [amount,setAmount]=useState('');const [currency,setCurrency]=useState('USD');const [description,setDescription]=useState('');const [date,setDate]=useState(today());const [categories,setCategories]=useState<LocalCategoryRecord[]>([]);const [categoryId,setCategoryId]=useState<string>();const [error,setError]=useState<string|null>(null);const load=useCallback(async()=>{if(user){const db=await getDatabase();setCategories(await listLocalCategories(db,user.id));}},[user]);useFocusEffect(useCallback(()=>{void load();},[load]));if(!authenticated||!user)return <Redirect href="/"/>;const save=async()=>{try{if(!description.trim()||!categoryId||!isValidExpenseDate(date))throw new Error('Complete all fields and use YYYY-MM-DD for the date.');const normalizedCurrency=currency.trim().toUpperCase();if(!/^[A-Z]{3}$/.test(normalizedCurrency))throw new Error('Currency must be a three-letter code.');const db=await getDatabase();await insertExpense(db,{userId:user.id,categoryId,amountMinor:amountToMinor(amount),currency:normalizedCurrency,description:description.trim(),expenseDate:date});router.back();}catch(cause){setError(cause instanceof Error?cause.message:'Unable to save expense.');}};return <ScrollView contentContainerStyle={styles.container}><Text style={styles.title}>New expense</Text><TextInput style={styles.input} placeholder="Amount (e.g. 12.34)" keyboardType="decimal-pad" value={amount} onChangeText={setAmount}/><TextInput style={styles.input} placeholder="Currency" autoCapitalize="characters" value={currency} onChangeText={setCurrency}/><TextInput style={styles.input} placeholder="Description" value={description} onChangeText={setDescription}/><TextInput style={styles.input} placeholder="YYYY-MM-DD" value={date} onChangeText={setDate}/><Text style={styles.label}>Category</Text>{categories.map(category=><Pressable key={category.id} style={[styles.category,categoryId===category.id&&styles.selected]} onPress={()=>setCategoryId(category.id)}><Text>{category.name}</Text></Pressable>)}{categories.length===0&&<Text>No cached categories available yet.</Text>}{error&&<Text style={styles.error}>{error}</Text>}<Button title="Save locally" onPress={()=>void save()}/></ScrollView>;}
const styles=StyleSheet.create({container:{padding:20,gap:10,backgroundColor:'#fff',flexGrow:1},title:{fontSize:28,fontWeight:'700',marginBottom:8},input:{borderWidth:1,borderColor:'#ccd3df',padding:12,borderRadius:6},label:{fontWeight:'600',marginTop:8},category:{borderWidth:1,borderColor:'#ccd3df',padding:12,borderRadius:6},selected:{backgroundColor:'#dbeafe',borderColor:'#2563eb'},error:{color:'#b42318'}});
