import type { PropsWithChildren } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, type TextInputProps, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors, radius, spacing } from './theme';

export function Card({children}:PropsWithChildren):React.ReactElement { return <View style={styles.card}>{children}</View>; }
export function AppButton({label,onPress,disabled=false,variant='primary'}:{label:string;onPress:()=>void;disabled?:boolean;variant?:'primary'|'secondary'|'danger'}):React.ReactElement { return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} style={[styles.button,styles[variant],disabled&&styles.disabled]}><Text style={[styles.buttonText,(variant==='secondary'||variant==='danger')&&styles.secondaryText]}>{label}</Text></Pressable>; }
export function FormInput({label,style,...props}:TextInputProps & {label?:string}):React.ReactElement { return <View style={styles.field}>{label&&<Text style={styles.fieldLabel}>{label}</Text>}<TextInput accessibilityLabel={label??props.placeholder} placeholderTextColor={colors.muted} style={[styles.input,style]} {...props}/></View>; }
export function IconAction({icon,label,onPress,disabled=false,tone='default'}:{icon:keyof typeof Ionicons.glyphMap;label:string;onPress:()=>void;disabled?:boolean;tone?:'default'|'danger'}):React.ReactElement { return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} hitSlop={8} style={[styles.iconAction,disabled&&styles.disabled]}><Ionicons name={icon} size={20} color={tone==='danger'?colors.danger:colors.accent}/></Pressable>; }
export function StateMessage({kind='empty',children}:{kind?:'loading'|'empty'|'error'|'offline';children:string}):React.ReactElement { return <View style={styles.state}>{kind==='loading'&&<ActivityIndicator color={colors.accent}/>}<Text style={[styles.stateText,kind==='error'&&styles.error]}>{children}</Text></View>; }
export function OfflineNotice():React.ReactElement { return <View style={styles.offline}><Text style={styles.offlineText}>Offline — cached data is available; category changes require a connection.</Text></View>; }
const styles=StyleSheet.create({card:{backgroundColor:colors.surface,borderRadius:radius.md,padding:spacing.md,borderWidth:1,borderColor:colors.border},button:{alignItems:'center',borderRadius:radius.sm,minHeight:46,justifyContent:'center',paddingHorizontal:spacing.md},primary:{backgroundColor:colors.accent},secondary:{backgroundColor:colors.surfaceRaised,borderWidth:1,borderColor:colors.border},danger:{backgroundColor:'#a9343d'},disabled:{opacity:.45},buttonText:{color:'#102016',fontWeight:'800'},secondaryText:{color:'#ffffff'},field:{gap:spacing.xs},fieldLabel:{color:colors.text,fontSize:14,fontWeight:'700'},input:{backgroundColor:colors.surface,borderColor:colors.border,borderWidth:1,borderRadius:radius.sm,color:colors.text,minHeight:48,paddingHorizontal:13,paddingVertical:11},iconAction:{alignItems:'center',borderColor:colors.border,borderRadius:radius.sm,borderWidth:1,justifyContent:'center',minHeight:40,minWidth:40,backgroundColor:colors.surfaceRaised},state:{alignItems:'center',gap:spacing.sm,padding:spacing.xl},stateText:{color:colors.muted,textAlign:'center'},error:{color:colors.danger},offline:{backgroundColor:'#40351d',borderRadius:radius.sm,padding:spacing.sm},offlineText:{color:colors.warning,fontSize:13}});
