import type { PropsWithChildren } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { colors, radius, spacing } from './theme';

export function Card({children}:PropsWithChildren):React.ReactElement { return <View style={styles.card}>{children}</View>; }
export function AppButton({label,onPress,disabled=false,variant='primary'}:{label:string;onPress:()=>void;disabled?:boolean;variant?:'primary'|'secondary'|'danger'}):React.ReactElement { return <Pressable disabled={disabled} onPress={onPress} style={[styles.button,styles[variant],disabled&&styles.disabled]}><Text style={[styles.buttonText,variant==='secondary'&&styles.secondaryText]}>{label}</Text></Pressable>; }
export function StateMessage({kind='empty',children}:{kind?:'loading'|'empty'|'error'|'offline';children:string}):React.ReactElement { return <View style={styles.state}>{kind==='loading'&&<ActivityIndicator color={colors.accent}/>}<Text style={[styles.stateText,kind==='error'&&styles.error]}>{children}</Text></View>; }
export function OfflineNotice():React.ReactElement { return <View style={styles.offline}><Text style={styles.offlineText}>Offline — cached data is available; category changes require a connection.</Text></View>; }
const styles=StyleSheet.create({card:{backgroundColor:colors.surface,borderRadius:radius.md,padding:spacing.md,borderWidth:1,borderColor:colors.border},button:{alignItems:'center',borderRadius:radius.sm,minHeight:46,justifyContent:'center',paddingHorizontal:spacing.md},primary:{backgroundColor:colors.accent},secondary:{backgroundColor:colors.surfaceRaised,borderWidth:1,borderColor:colors.border},danger:{backgroundColor:'#4a2529'},disabled:{opacity:.45},buttonText:{color:'#102016',fontWeight:'800'},secondaryText:{color:colors.text},state:{alignItems:'center',gap:spacing.sm,padding:spacing.xl},stateText:{color:colors.muted,textAlign:'center'},error:{color:colors.danger},offline:{backgroundColor:'#40351d',borderRadius:radius.sm,padding:spacing.sm},offlineText:{color:colors.warning,fontSize:13}});
