import { ConflictException, NotFoundException } from '@nestjs/common';
import { SyncService } from './sync.service';
import { ExpenseSyncOperationType, SyncExpenseDto } from './dto/sync-expense.dto';

const user = '11111111-1111-4111-8111-111111111111'; const other = '22222222-2222-4222-8222-222222222222'; const category = '33333333-3333-4333-8333-333333333333'; const id = '44444444-4444-4444-8444-444444444444';
describe('SyncService',()=>{
 let operations:any[];let expenses:any[];let categories:any[];let service:SyncService;let db:any;
 const dto=(operationId:string,type:ExpenseSyncOperationType,payload:any={},baseVersion?:number):SyncExpenseDto=>({operationId,operationType:type,entityId:id,payload,baseVersion});
 beforeEach(()=>{operations=[];expenses=[];categories=[{id:category,userId:user}];const processed={findUnique:jest.fn(async({where}:any)=>operations.find(x=>x.userId===where.userId_operationId.userId&&x.operationId===where.userId_operationId.operationId)??null),create:jest.fn(async({data}:any)=>{const x={...data};operations.push(x);return x;})};const expense={findUnique:jest.fn(async({where}:any)=>expenses.find(x=>x.id===where.id)??null),findFirst:jest.fn(async({where}:any)=>expenses.find(x=>x.id===where.id&&x.userId===where.userId)??null),create:jest.fn(async({data}:any)=>{const x={...data,createdAt:new Date(),updatedAt:new Date(),deletedAt:null};expenses.push(x);return x;}),update:jest.fn(async({where,data}:any)=>{const x=expenses.find(e=>e.id===where.id);Object.assign(x,data,{version:x.version+(data.version?.increment??0)});return x;})};db={processedOperation:processed,expense,category:{findFirst:jest.fn(async({where}:any)=>categories.find(c=>c.id===where.id&&c.userId===where.userId)??null)} };db.$transaction=async(cb:any)=>cb(db);service=new SyncService(db);});
 it('creates with client id and replays identical operations',async()=>{const op='55555555-5555-4555-8555-555555555555';const input=dto(op,ExpenseSyncOperationType.CREATE,{categoryId:category,amountMinor:1,currency:'USD',description:'x',expenseDate:'2026-01-01'});const first:any=await service.syncExpense(user,input);const replay:any=await service.syncExpense(user,input);expect(first.expense.id).toBe(id);expect(replay).toMatchObject({status:'APPLIED',expense:{id}});expect(expenses).toHaveLength(1);});
 it('rejects changed operation requests and foreign categories',async()=>{const op='55555555-5555-4555-8555-555555555555';await service.syncExpense(user,dto(op,ExpenseSyncOperationType.CREATE,{categoryId:category,amountMinor:1,currency:'USD',description:'x',expenseDate:'2026-01-01'}));await expect(service.syncExpense(user,dto(op,ExpenseSyncOperationType.CREATE,{categoryId:category,amountMinor:2,currency:'USD',description:'x',expenseDate:'2026-01-01'}))).rejects.toBeInstanceOf(ConflictException);await expect(service.syncExpense(other,dto('66666666-6666-4666-8666-666666666666',ExpenseSyncOperationType.CREATE,{categoryId:category}))).rejects.toBeInstanceOf(NotFoundException);});
 it('returns current state for stale update/delete and soft deletes successful deletes',async()=>{expenses.push({id,userId:user,categoryId:category,version:2});const stale:any=await service.syncExpense(user,dto('77777777-7777-4777-8777-777777777777',ExpenseSyncOperationType.UPDATE,{description:'x'},1));expect(stale.status).toBe('CONFLICT');const deleted:any=await service.syncExpense(user,dto('88888888-8888-4888-8888-888888888888',ExpenseSyncOperationType.DELETE,{},2));expect(deleted.expense.version).toBe(3);expect(deleted.expense.deletedAt).toBeInstanceOf(Date);});
});
