import type { GroupBalance, SafeUser, SettlementSuggestion } from '../../api/group-service';
import { majorToMinor } from '../currency/amount';
export interface ShareInput {userId:string;amountMinor:string}
export function validateGroupExpenseForm(input:{amountMinor:string;currency:string;description:string;expenseDate:string;categoryId:string;paidByUserId:string;shares:readonly ShareInput[]}){const amount=Number(input.amountMinor);if(!Number.isInteger(amount)||amount<1)return {value:null,error:'Enter a positive whole amount in minor units.'};if(!/^[A-Z]{3}$/.test(input.currency.trim().toUpperCase()))return {value:null,error:'Currency must be a three-letter uppercase code.'};if(!input.description.trim()||!input.categoryId||!input.paidByUserId)return {value:null,error:'Complete the description, category, and payer.'};const seen=new Set<string>();let total=0;for(const share of input.shares){const value=Number(share.amountMinor);if(seen.has(share.userId))return {value:null,error:'Each member can have only one share.'};seen.add(share.userId);if(!Number.isInteger(value)||value<1)return {value:null,error:'Every share must be a positive whole amount.'};total+=value;}if(total!==amount)return {value:null,error:'Shares must add up exactly to the expense amount.'};return {value:{amountMinor:amount,currency:input.currency.trim().toUpperCase(),description:input.description.trim(),expenseDate:input.expenseDate,categoryId:input.categoryId,paidByUserId:input.paidByUserId,shares:input.shares.map(s=>({userId:s.userId,amountMinor:Number(s.amountMinor)}))},error:null};}
export interface MajorShareInput { userId:string; amount:string }
export function validateGroupExpenseMajorForm(input:{amount:string;currency:string;description:string;expenseDate:string;categoryId:string;paidByUserId:string;shares:readonly MajorShareInput[]}){try{return validateGroupExpenseForm({...input,amountMinor:String(majorToMinor(input.amount)),shares:input.shares.map(share=>({userId:share.userId,amountMinor:String(majorToMinor(share.amount))}))});}catch(cause){return {value:null,error:cause instanceof Error?cause.message:'Enter a valid amount.'};}}
export function settlementAmountToMinor(value:string):number{return majorToMinor(value);}
export const balanceLabel=(balance:GroupBalance)=>balance.netMinor<0?`Owes ${Math.abs(balance.netMinor)}`:balance.netMinor>0?`Is owed ${balance.netMinor}`:'Settled up';
export const balanceViewModel=(balance:GroupBalance)=>({...balance,label:balanceLabel(balance),tone:balance.netMinor<0?'debt':balance.netMinor>0?'credit':'settled'} as const);
export const suggestionViewModel=(suggestion:SettlementSuggestion,members:readonly SafeUser[])=>({from:members.find(m=>m.id===suggestion.fromUserId)?.name??'Member',to:members.find(m=>m.id===suggestion.toUserId)?.name??'Member',amountMinor:suggestion.amountMinor});
export function groupApiError(error:unknown):string {const value=error as {status?:number;message?:string};if(value.status===409)return value.message??'This change conflicts with the latest group balance.';return value.message??'Unable to complete the group request.';}
