import test from 'node:test';
import assert from 'node:assert/strict';
import { balanceLabel, balanceViewModel, groupApiError, settlementAmountToMinor, suggestionViewModel, validateGroupExpenseForm, validateGroupExpenseMajorForm } from './group-logic';
const valid={amountMinor:'5000',currency:'PKR',description:'Dinner',expenseDate:'2026-08-29',categoryId:'c',paidByUserId:'p',shares:[{userId:'a',amountMinor:'2500'},{userId:'b',amountMinor:'2500'}]};
test('validates share totals and duplicate members',()=>{assert.equal(validateGroupExpenseForm(valid).error,null);assert.equal(validateGroupExpenseForm({...valid,shares:[{userId:'a',amountMinor:'2500'},{userId:'a',amountMinor:'2500'}]}).error,'Each member can have only one share.');assert.equal(validateGroupExpenseForm({...valid,shares:[{userId:'a',amountMinor:'100'}]}).error,'Shares must add up exactly to the expense amount.');});
test('converts group and settlement major-unit form amounts safely',()=>{const input={amount:'20.50',currency:'PKR',description:'Dinner',expenseDate:'2026-08-29',categoryId:'c',paidByUserId:'p',shares:[{userId:'a',amount:'10.25'},{userId:'b',amount:'10.25'}]};const result=validateGroupExpenseMajorForm(input);assert.equal(result.value?.amountMinor,2050);assert.deepEqual(result.value?.shares.map(share=>share.amountMinor),[1025,1025]);assert.equal(settlementAmountToMinor('20.50'),2050);assert.match(validateGroupExpenseMajorForm({...input,amount:'20.123'}).error??'',/no more than two decimal places/);});
test('maps balance debt and credit labels',()=>{const debt={userId:'a',name:'A',email:'a',paidMinor:0,owedMinor:50,settledOutgoingMinor:0,settledIncomingMinor:0,netMinor:-50};assert.equal(balanceLabel(debt),'Owes 50');assert.equal(balanceViewModel({...debt,netMinor:25}).tone,'credit');});
test('maps settlement suggestions to safe member names',()=>assert.deepEqual(suggestionViewModel({fromUserId:'a',toUserId:'b',amountMinor:40},[{id:'a',name:'Ali',email:'a'},{id:'b',name:'Bea',email:'b'}]),{from:'Ali',to:'Bea',amountMinor:40}));
test('maps group API conflict errors',()=>assert.equal(groupApiError({status:409,message:'Settlement conflicted.'}),'Settlement conflicted.'));
